"use client";

import { FormEvent, useEffect, useState } from "react";
import { getCurrentAgency } from "../lib/currentAgency";
import { isSupabaseConfigured, supabaseBrowser } from "../lib/supabaseBrowser";

type Lead={id:string;name:string|null;phone:string|null;email:string|null};
type Permission={whatsapp_allowed:boolean;email_allowed:boolean;sms_allowed:boolean;automated_property_alerts_allowed:boolean;consent_source:string|null;consent_at:string|null;revoked_at:string|null};
const empty:Permission={whatsapp_allowed:false,email_allowed:false,sms_allowed:false,automated_property_alerts_allowed:false,consent_source:null,consent_at:null,revoked_at:null};

export default function AdminBuyerConsent(){
  const [agencyId,setAgencyId]=useState(""); const [leads,setLeads]=useState<Lead[]>([]); const [leadId,setLeadId]=useState(""); const [permission,setPermission]=useState<Permission>(empty); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
  async function load(){if(!supabaseBrowser||!isSupabaseConfigured)return; const agency=await getCurrentAgency(); if(!agency)return setMessage("Imobiliária ativa não encontrada."); setAgencyId(agency.agencyId); const result=await supabaseBrowser.from("leads").select("id,name,phone,email").eq("agency_id",agency.agencyId).order("created_at",{ascending:false}).limit(200); if(result.error)return setMessage(result.error.message); setLeads((result.data||[]) as Lead[]);}
  useEffect(()=>{void load();},[]);
  useEffect(()=>{void(async()=>{if(!supabaseBrowser||!agencyId||!leadId){setPermission(empty);return;} const result=await supabaseBrowser.from("lead_contact_permissions").select("whatsapp_allowed,email_allowed,sms_allowed,automated_property_alerts_allowed,consent_source,consent_at,revoked_at").eq("agency_id",agencyId).eq("lead_id",leadId).maybeSingle(); if(result.error&&!['42P01','42703'].includes(result.error.code||''))return setMessage(result.error.message); setPermission(result.data?result.data as Permission:empty);})();},[agencyId,leadId]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault(); if(!supabaseBrowser||!agencyId||!leadId)return; const form=new FormData(event.currentTarget); const alerts=form.get("alerts")==="on"; const payload={agency_id:agencyId,lead_id:leadId,whatsapp_allowed:form.get("whatsapp")==="on",email_allowed:form.get("email")==="on",sms_allowed:form.get("sms")==="on",automated_property_alerts_allowed:alerts,consent_source:String(form.get("source")||"").trim()||"registro interno",consent_at:alerts?(permission.consent_at||new Date().toISOString()):permission.consent_at,revoked_at:alerts?null:new Date().toISOString(),updated_at:new Date().toISOString()}; setSaving(true); setMessage(""); const result=await supabaseBrowser.from("lead_contact_permissions").upsert(payload,{onConflict:"agency_id,lead_id"}); setSaving(false); if(result.error)return setMessage(result.error.message); setPermission({...payload} as Permission); setMessage(alerts?"Consentimento registrado.":"Alertas automáticos desativados para este contato.");}
  return <div className="adminPanel" id="consentimento-compradores"><div className="adminPanelHeader"><div><span className="eyebrow">CONSENTIMENTO</span><h2>Permissões de contato dos compradores</h2><p>Controle por cliente quais canais podem ser usados e se ele autorizou alertas automáticos de novos imóveis compatíveis.</p></div></div>
  <form className="propertyForm" onSubmit={save}><label>Comprador<select value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">Selecione...</option>{leads.map(l=><option key={l.id} value={l.id}>{l.name||"Contato sem nome"} · {l.phone||l.email||"sem canal"}</option>)}</select></label>
  {leadId?<><div className="formGrid three"><label className="checkLabel"><input name="whatsapp" type="checkbox" defaultChecked={permission.whatsapp_allowed} key={`w-${leadId}-${permission.whatsapp_allowed}`}/> WhatsApp autorizado</label><label className="checkLabel"><input name="email" type="checkbox" defaultChecked={permission.email_allowed} key={`e-${leadId}-${permission.email_allowed}`}/> E-mail autorizado</label><label className="checkLabel"><input name="sms" type="checkbox" defaultChecked={permission.sms_allowed} key={`s-${leadId}-${permission.sms_allowed}`}/> SMS autorizado</label></div><label className="checkLabel"><input name="alerts" type="checkbox" defaultChecked={permission.automated_property_alerts_allowed&&!permission.revoked_at} key={`a-${leadId}-${permission.automated_property_alerts_allowed}-${permission.revoked_at||''}`}/> Cliente autorizou alertas automáticos de imóveis compatíveis</label><label>Origem do consentimento<input name="source" defaultValue={permission.consent_source||""} placeholder="Ex.: WhatsApp, formulário, atendimento presencial" /></label><div className="formActions"><button className="button primary" disabled={saving}>{saving?"Salvando...":"Salvar permissões"}</button></div></>:null}</form>{message?<div className="formMessage">{message}</div>:null}</div>;
}
