"use client";

import { useEffect,useState } from "react";
import { getCurrentAgency } from "../lib/currentAgency";
import { isSupabaseConfigured,supabaseBrowser } from "../lib/supabaseBrowser";

type Row={broker_id:string;broker_name:string;properties_total:number;properties_available:number;leads_total:number;visits_scheduled:number;visits_completed:number;visits_no_show:number;deals_won:number;deals_lost:number;close_rate_percent:number|null;avg_first_response_minutes:number|null};
function time(value:number|null){if(value==null)return "—";if(value<60)return `${Math.round(value)} min`;return `${Math.floor(value/60)}h ${Math.round(value%60)}min`;}

export default function AdminBrokerPerformance(){const [rows,setRows]=useState<Row[]>([]);const [message,setMessage]=useState("");useEffect(()=>{void(async()=>{if(!supabaseBrowser||!isSupabaseConfigured)return;const agency=await getCurrentAgency();if(!agency)return setMessage("Imobiliária ativa não encontrada.");const result=await supabaseBrowser.from("agency_broker_performance").select("broker_id,broker_name,properties_total,properties_available,leads_total,visits_scheduled,visits_completed,visits_no_show,deals_won,deals_lost,close_rate_percent,avg_first_response_minutes").eq("agency_id",agency.agencyId).order("deals_won",{ascending:false});if(result.error&&!['42P01','42703'].includes(result.error.code||''))return setMessage(result.error.message);setRows((result.data||[]) as Row[]);})();},[]);const totalWon=rows.reduce((sum,row)=>sum+Number(row.deals_won||0),0);const totalLeads=rows.reduce((sum,row)=>sum+Number(row.leads_total||0),0);const totalVisits=rows.reduce((sum,row)=>sum+Number(row.visits_completed||0),0);return <div className="adminPanel adminOnly" id="desempenho-corretores"><div className="adminPanelHeader"><div><span className="eyebrow">EQUIPE COMERCIAL</span><h2>Desempenho dos corretores</h2><p>Compare carteira, atendimento, visitas e fechamentos sem misturar dados entre imobiliárias.</p></div><span>{rows.length} corretor(es)</span></div><div className="adminMetrics planMetrics"><article><span>Corretores ativos</span><strong>{rows.length}</strong></article><article><span>Leads distribuídos</span><strong>{totalLeads}</strong></article><article><span>Visitas concluídas</span><strong>{totalVisits}</strong></article><article><span>Negócios fechados</span><strong>{totalWon}</strong></article></div>{rows.length?<div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Corretor</th><th>Imóveis</th><th>Leads</th><th>Próximas</th><th>Concluídas</th><th>Ausências</th><th>Fechados</th><th>Conversão</th><th>1ª resposta</th></tr></thead><tbody>{rows.map(row=><tr key={row.broker_id}><td><strong>{row.broker_name}</strong></td><td>{row.properties_available} disponíveis / {row.properties_total}</td><td>{row.leads_total}</td><td>{row.visits_scheduled}</td><td>{row.visits_completed}</td><td>{row.visits_no_show}</td><td>{row.deals_won}</td><td>{Number(row.close_rate_percent||0).toLocaleString('pt-BR')}%</td><td>{time(row.avg_first_response_minutes)}</td></tr>)}</tbody></table></div>:<div className="formNotice">Os indicadores aparecerão quando houver corretores e atendimentos registrados.</div>}{message?<div className="formMessage">{message}</div>:null}</div>}
