"use client";

import { FormEvent, useEffect, useState } from "react";
import { getCurrentAgency } from "../lib/currentAgency";
import { isSupabaseConfigured, supabaseBrowser } from "../lib/supabaseBrowser";

type Settings={enabled:boolean;auto_contact:boolean;min_match_score:number;cooldown_hours:number;channels:string[];require_explicit_consent:boolean;notify_broker:boolean};
type Opportunity={id:string;match_score:number;status:string;channel:string|null;ai_message:string|null;created_at:string;leads?:{name?:string|null;phone?:string|null;email?:string|null}|null;properties?:{code?:string|null;title?:string|null;price?:number|null}|null};
type Delivery={attempts:number;sent:number;delivered:number;read:number;failed:number;attempts_this_month:number};
const defaults:Settings={enabled:false,auto_contact:false,min_match_score:80,cooldown_hours:72,channels:["whatsapp"],require_explicit_consent:true,notify_broker:true};
const emptyDelivery:Delivery={attempts:0,sent:0,delivered:0,read:0,failed:0,attempts_this_month:0};

export default function AdminBuyerOutreach(){
  const [agencyId,setAgencyId]=useState(""); const [settings,setSettings]=useState<Settings>(defaults); const [items,setItems]=useState<Opportunity[]>([]); const [delivery,setDelivery]=useState<Delivery>(emptyDelivery); const [entitled,setEntitled]=useState<boolean|null>(null); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false); const [generating,setGenerating]=useState("");
  async function load(){if(!supabaseBrowser||!isSupabaseConfigured)return; const agency=await getCurrentAgency(); if(!agency)return setMessage("Imobiliária ativa não encontrada."); setAgencyId(agency.agencyId); const [s,o,d,e]=await Promise.all([
    supabaseBrowser.from("buyer_outreach_settings").select("enabled,auto_contact,min_match_score,cooldown_hours,channels,require_explicit_consent,notify_broker").eq("agency_id",agency.agencyId).maybeSingle(),
    supabaseBrowser.from("buyer_property_opportunities").select("id,match_score,status,channel,ai_message,created_at,leads(name,phone,email),properties(code,title,price)").eq("agency_id",agency.agencyId).order("created_at",{ascending:false}).limit(60),
    supabaseBrowser.from("agency_buyer_outreach_delivery_summary").select("attempts,sent,delivered,read,failed,attempts_this_month").eq("agency_id",agency.agencyId).maybeSingle(),
    supabaseBrowser.rpc("agency_has_plan_feature",{p_agency_id:agency.agencyId,p_feature_key:"ai_buyer_outreach",p_default:false}),
  ]); if(s.error&&!['42P01','42703'].includes(s.error.code||''))setMessage(s.error.message); if(s.data)setSettings(s.data as Settings); if(o.error&&!['42P01','42703'].includes(o.error.code||''))setMessage(o.error.message); setItems((o.data||[]) as unknown as Opportunity[]); if(d.data)setDelivery(d.data as Delivery); setEntitled(e.error?null:Boolean(e.data));}
  useEffect(()=>{void load();},[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault(); if(!supabaseBrowser||!agencyId)return; if(entitled===false)return setMessage("O plano atual não inclui IA de oportunidades para compradores."); const form=new FormData(event.currentTarget); const next:Settings={enabled:form.get("enabled")==="on",auto_contact:form.get("auto_contact")==="on",min_match_score:Math.max(0,Math.min(100,Number(form.get("min_match_score")||80))),cooldown_hours:Math.max(1,Math.min(720,Number(form.get("cooldown_hours")||72))),channels:[form.get("whatsapp")==="on"?"whatsapp":"",form.get("email")==="on"?"email":""].filter(Boolean),require_explicit_consent:form.get("require_explicit_consent")==="on",notify_broker:form.get("notify_broker")==="on"}; setSaving(true); setMessage(""); const {error}=await supabaseBrowser.from("buyer_outreach_settings").upsert({agency_id:agencyId,...next,updated_at:new Date().toISOString()},{onConflict:"agency_id"}); setSaving(false); if(error)return setMessage(error.message); setSettings(next); setMessage("Configuração de oportunidades salva.");}
  async function changeStatus(id:string,status:string){if(!supabaseBrowser||!agencyId)return; const payload:any={status,updated_at:new Date().toISOString()}; if(status==="approved"){payload.approved_at=new Date().toISOString(); const user=await supabaseBrowser.auth.getUser(); payload.approved_by=user.data.user?.id||null;} if(status==="skipped")payload.skip_reason="Ignorado manualmente"; const {error}=await supabaseBrowser.from("buyer_property_opportunities").update(payload).eq("id",id).eq("agency_id",agencyId); if(error)return setMessage(error.message); await load();}
  async function generateMessage(id:string){if(!supabaseBrowser)return; if(entitled===false)return setMessage("O plano atual não inclui este recurso."); setGenerating(id); setMessage(""); const {data,error}=await supabaseBrowser.functions.invoke("generate-buyer-opportunity-message",{body:{opportunity_id:id}}); setGenerating(""); if(error)return setMessage(error.message); if(data?.error)return setMessage(String(data.error)); setMessage("Mensagem de oportunidade gerada para revisão."); await load();}
  return <div className="adminPanel adminOnly" id="oportunidades-ia"><div className="adminPanelHeader"><div><span className="eyebrow">IA COMERCIAL</span><h2>Oportunidades automáticas para compradores</h2><p>Novos imóveis e alterações relevantes podem gerar oportunidades para clientes com perfil compatível. O envio automático só deve ocorrer com canal autorizado, consentimento e plano habilitado.</p></div><span>{entitled===false?"Fora do plano":`${items.filter(i=>i.status==="queued"||i.status==="review").length} pendente(s)`}</span></div>
  <div className="adminMetrics planMetrics"><article><span>Oportunidades</span><strong>{items.length}</strong><small>últimas registradas</small></article><article><span>Tentativas no mês</span><strong>{delivery.attempts_this_month}</strong><small>envios preparados/processados</small></article><article><span>Enviadas</span><strong>{delivery.sent}</strong><small>inclui entregues/lidas</small></article><article><span>Falhas</span><strong>{delivery.failed}</strong><small>para revisão</small></article></div>
  <form className="propertyForm" onSubmit={save}><div className="formGrid three"><label>Pontuação mínima<input name="min_match_score" type="number" min="0" max="100" defaultValue={settings.min_match_score}/></label><label>Intervalo mínimo (horas)<input name="cooldown_hours" type="number" min="1" max="720" defaultValue={settings.cooldown_hours}/></label><label className="checkLabel"><input name="enabled" type="checkbox" defaultChecked={settings.enabled}/> Ativar detecção de oportunidades</label></div>
  <div className="formGrid"><label className="checkLabel"><input name="whatsapp" type="checkbox" defaultChecked={settings.channels.includes("whatsapp")}/> WhatsApp</label><label className="checkLabel"><input name="email" type="checkbox" defaultChecked={settings.channels.includes("email")}/> E-mail</label></div>
  <div className="formGrid"><label className="checkLabel"><input name="require_explicit_consent" type="checkbox" defaultChecked={settings.require_explicit_consent}/> Exigir consentimento explícito</label><label className="checkLabel"><input name="notify_broker" type="checkbox" defaultChecked={settings.notify_broker}/> Avisar corretor responsável</label><label className="checkLabel"><input name="auto_contact" type="checkbox" defaultChecked={settings.auto_contact}/> Permitir envio automático quando configurado</label></div>
  <div className="formActions"><button className="button primary" disabled={saving||entitled===false}>{saving?"Salvando...":"Salvar configuração"}</button></div></form>
  {message?<div className="formMessage">{message}</div>:null}
  <div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Comprador</th><th>Imóvel</th><th>Match</th><th>Canal</th><th>Situação</th><th>Mensagem IA</th><th>Ações</th></tr></thead><tbody>{items.length?items.map(item=><tr key={item.id}><td><strong>{item.leads?.name||"Contato sem nome"}</strong><small className="tableSub">{item.leads?.phone||item.leads?.email||"sem canal"}</small></td><td><strong>{item.properties?.code||"—"}</strong><small className="tableSub">{item.properties?.title||"Imóvel"}</small></td><td>{item.match_score}%</td><td>{item.channel||"revisar"}</td><td><span className="statusPill">{item.status}</span></td><td><small className="tableSub">{item.ai_message?item.ai_message.slice(0,140):"Ainda não gerada"}</small></td><td><div className="accessActions"><button className="miniButton" onClick={()=>void generateMessage(item.id)} disabled={generating===item.id||entitled===false}>{generating===item.id?"Gerando...":"Gerar texto"}</button>{item.status!=="sent"&&item.status!=="approved"?<button className="miniButton" onClick={()=>void changeStatus(item.id,"approved")}>Aprovar</button>:null}{item.status!=="sent"&&item.status!=="skipped"?<button className="miniButton muted" onClick={()=>void changeStatus(item.id,"skipped")}>Ignorar</button>:null}</div></td></tr>):<tr><td colSpan={7}>Nenhuma oportunidade registrada ainda.</td></tr>}</tbody></table></div>
  <div className="formMessage">A geração do texto já está preparada. O disparo real continuará bloqueado até existir provedor configurado e autorização válida do comprador.</div></div>;
}
