"use client";

import { useEffect,useState } from "react";
import { getCurrentAgency } from "../lib/currentAgency";
import { isSupabaseConfigured,supabaseBrowser } from "../lib/supabaseBrowser";

type Row={property_id:string;code:string;title:string;status:string;publication_state:string;price:number;favorites_count:number;leads_count:number;visits_count:number;completed_visits_count:number;upcoming_visits_count:number;won_count:number;leads_last_30d:number;days_published:number|null};

export default function AdminPropertyPerformance(){const [rows,setRows]=useState<Row[]>([]);const [message,setMessage]=useState("");useEffect(()=>{void(async()=>{if(!supabaseBrowser||!isSupabaseConfigured)return;const agency=await getCurrentAgency();if(!agency)return setMessage("Imobiliária ativa não encontrada.");const result=await supabaseBrowser.from("agency_property_commercial_performance").select("property_id,code,title,status,publication_state,price,favorites_count,leads_count,visits_count,completed_visits_count,upcoming_visits_count,won_count,leads_last_30d,days_published").eq("agency_id",agency.agencyId).order("leads_count",{ascending:false}).limit(100);if(result.error&&!['42P01','42703'].includes(result.error.code||''))return setMessage(result.error.message);setRows((result.data||[]) as Row[]);})();},[]);const totalLeads=rows.reduce((sum,row)=>sum+Number(row.leads_count||0),0);const totalVisits=rows.reduce((sum,row)=>sum+Number(row.completed_visits_count||0),0);const totalWon=rows.reduce((sum,row)=>sum+Number(row.won_count||0),0);const totalFavorites=rows.reduce((sum,row)=>sum+Number(row.favorites_count||0),0);return <div className="adminPanel adminOnly" id="desempenho-imoveis"><div className="adminPanelHeader"><div><span className="eyebrow">CATÁLOGO</span><h2>Desempenho dos imóveis</h2><p>Veja quais anúncios geram mais favoritos, contatos, visitas e negócios.</p></div><span>{rows.length} imóvel(is)</span></div><div className="adminMetrics planMetrics"><article><span>Favoritos</span><strong>{totalFavorites}</strong></article><article><span>Leads</span><strong>{totalLeads}</strong></article><article><span>Visitas concluídas</span><strong>{totalVisits}</strong></article><article><span>Negócios fechados</span><strong>{totalWon}</strong></article></div>{rows.length?<div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Imóvel</th><th>Favoritos</th><th>Leads</th><th>Últimos 30d</th><th>Visitas</th><th>Próximas</th><th>Fechados</th><th>Dias publicado</th></tr></thead><tbody>{rows.map(r=><tr key={r.property_id}><td><strong>{r.code}</strong><small className="tableSub">{r.title}</small></td><td>{r.favorites_count}</td><td>{r.leads_count}</td><td>{r.leads_last_30d}</td><td>{r.completed_visits_count}</td><td>{r.upcoming_visits_count}</td><td>{r.won_count}</td><td>{r.days_published??"—"}</td></tr>)}</tbody></table></div>:<div className="formNotice">Os indicadores aparecerão conforme o catálogo receber favoritos e contatos.</div>}{message?<div className="formMessage">{message}</div>:null}</div>}
