"use client";

import { useEffect,useMemo,useState } from "react";
import { getCurrentAgency } from "../lib/currentAgency";
import { isSupabaseConfigured,supabaseBrowser } from "../lib/supabaseBrowser";

type Property={id:string;code:string;title:string};type Item={id:string;property_id:string;label:string;status:string;expires_at:string|null;notes:string|null};
const statusLabels:Record<string,string>={pending:"Pendente",received:"Recebido",approved:"Aprovado",rejected:"Rejeitado",not_applicable:"Não se aplica"};
export default function AdminPropertyDocumentChecklist(){const [agencyId,setAgencyId]=useState("");const [properties,setProperties]=useState<Property[]>([]);const [propertyId,setPropertyId]=useState("");const [items,setItems]=useState<Item[]>([]);const [message,setMessage]=useState("");const [loading,setLoading]=useState(false);const [savingId,setSavingId]=useState("");
async function loadBase(){if(!supabaseBrowser||!isSupabaseConfigured)return;const a=await getCurrentAgency();if(!a)return setMessage("Imobiliária ativa não encontrada.");setAgencyId(a.agencyId);const r=await supabaseBrowser.from("properties").select("id,code,title").eq("agency_id",a.agencyId).order("updated_at",{ascending:false}).limit(200);if(r.error)return setMessage(r.error.message);setProperties((r.data||[]) as Property[]);}useEffect(()=>{void loadBase();},[]);
async function loadItems(id:string){setPropertyId(id);setItems([]);setMessage("");if(!supabaseBrowser||!id)return;setLoading(true);const seed=await supabaseBrowser.rpc("ensure_default_property_document_items",{p_property_id:id});if(seed.error){setLoading(false);return setMessage(`Não foi possível preparar o checklist: ${seed.error.message}`);}const r=await supabaseBrowser.from("property_document_items").select("id,property_id,label,status,expires_at,notes").eq("agency_id",agencyId).eq("property_id",id).order("created_at");setLoading(false);if(r.error)return setMessage(r.error.message);setItems((r.data||[]) as Item[]);}
async function update(item:Item,patch:Partial<Item>){if(!supabaseBrowser)return;setSavingId(item.id);setMessage("");const r=await supabaseBrowser.from("property_document_items").update(patch).eq("id",item.id).eq("agency_id",agencyId);setSavingId("");if(r.error)return setMessage(r.error.message);setItems(c=>c.map(x=>x.id===item.id?{...x,...patch}:x));setMessage("Checklist atualizado.");}
const approved=items.filter(i=>i.status==='approved').length;const pending=items.filter(i=>i.status==='pending'||i.status==='received').length;const rejected=items.filter(i=>i.status==='rejected').length;const expired=useMemo(()=>items.filter(i=>i.expires_at&&new Date(`${i.expires_at}T12:00:00`).getTime()<Date.now()).length,[items]);
return <div className="adminPanel" id="documentacao-imovel"><div className="adminPanelHeader"><div><span className="eyebrow">DOCUMENTAÇÃO DO IMÓVEL</span><h2>Checklist documental</h2><p>Controle matrícula, IPTU, documentos do proprietário, ônus e demais itens antes da negociação.</p></div><span>{approved}/{items.length||0} aprovados</span></div>{propertyId?<div className="adminMetrics planMetrics"><article><span>Aprovados</span><strong>{approved}</strong></article><article><span>Pendentes</span><strong>{pending}</strong></article><article><span>Rejeitados</span><strong>{rejected}</strong></article><article><span>Vencidos</span><strong>{expired}</strong></article></div>:null}{isSupabaseConfigured?<><div className="adminFilters"><select value={propertyId} onChange={e=>void loadItems(e.target.value)}><option value="">Selecione o imóvel</option>{properties.map(p=><option key={p.id} value={p.id}>{p.code} · {p.title}</option>)}</select>{loading?<span>Carregando checklist...</span>:null}</div>{propertyId?<div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Documento</th><th>Status</th><th>Validade</th><th>Observação</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><strong>{i.label}</strong>{savingId===i.id?<small className="tableSub">Salvando...</small>:null}</td><td><select value={i.status} disabled={savingId===i.id} onChange={e=>void update(i,{status:e.target.value})}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td><input type="date" value={i.expires_at||""} disabled={savingId===i.id} onChange={e=>void update(i,{expires_at:e.target.value||null})}/></td><td><input value={i.notes||""} disabled={savingId===i.id} onBlur={e=>void update(i,{notes:e.target.value||null})} onChange={e=>setItems(c=>c.map(x=>x.id===i.id?{...x,notes:e.target.value}:x))} placeholder="Observação"/></td></tr>)}{!items.length&&!loading?<tr><td colSpan={4}>Nenhum item disponível para este imóvel.</td></tr>:null}</tbody></table></div>:null}</>:null}{message?<div className="formMessage">{message}</div>:null}</div>}
