"use client";

import { FormEvent, useEffect, useState } from "react";
import { getCurrentAgency } from "../lib/currentAgency";
import { isSupabaseConfigured, supabaseBrowser } from "../lib/supabaseBrowser";

type Lead={id:string;name:string|null};
type Match={lead_id:string;property_id:string;code:string;title:string;price:number;match_score:number};

export default function AdminBuyerPreferences(){
  const [agencyId,setAgencyId]=useState(""); const [leads,setLeads]=useState<Lead[]>([]); const [matches,setMatches]=useState<Match[]>([]); const [selectedLead,setSelectedLead]=useState(""); const [message,setMessage]=useState("");
  async function load(){ if(!supabaseBrowser||!isSupabaseConfigured)return; const agency=await getCurrentAgency(); if(!agency)return setMessage("Imobiliária ativa não encontrada."); setAgencyId(agency.agencyId); const [leadResult,matchResult]=await Promise.all([
    supabaseBrowser.from("leads").select("id,name").eq("agency_id",agency.agencyId).order("created_at",{ascending:false}).limit(150),
    supabaseBrowser.from("lead_property_match_candidates").select("lead_id,property_id,code,title,price,match_score").eq("agency_id",agency.agencyId).order("match_score",{ascending:false}).limit(100),
  ]); if(leadResult.error&&!['42P01'].includes(leadResult.error.code||''))return setMessage(leadResult.error.message); setLeads((leadResult.data||[]) as Lead[]); setMatches((matchResult.data||[]) as Match[]); }
  useEffect(()=>{void load();},[]);
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault(); if(!supabaseBrowser||!agencyId)return; const f=new FormData(e.currentTarget); const leadId=String(f.get("lead_id")||""); if(!leadId)return setMessage("Selecione o contato."); const payload={agency_id:agencyId,lead_id:leadId,purpose:String(f.get("purpose")||"")||null,zone:String(f.get("zone")||"")||null,segment:String(f.get("segment")||"")||null,min_price:Number(f.get("min_price")||0)||null,max_price:Number(f.get("max_price")||0)||null,min_bedrooms:Number(f.get("min_bedrooms")||0)||null,min_parking:Number(f.get("min_parking")||0)||null,notes:String(f.get("notes")||"").trim()||null,active:true}; const r=await supabaseBrowser.from("lead_property_preferences").upsert(payload,{onConflict:"agency_id,lead_id"}); if(r.error)return setMessage(r.error.message); setSelectedLead(leadId); setMessage("Preferências salvas. Matching atualizado."); await load();}
  const visible=selectedLead?matches.filter(m=>m.lead_id===selectedLead).slice(0,10):[];
  return <div className="adminPanel" id="perfil-compra"><div className="adminPanelHeader"><div><span className="eyebrow">MATCH COMERCIAL</span><h2>Perfil de compra</h2><p>Registre o que o cliente procura e veja imóveis disponíveis com maior aderência.</p></div><span>{isSupabaseConfigured?`${matches.length} combinação(ões)`:"Modo demonstração"}</span></div>
  {isSupabaseConfigured?<><form className="propertyForm" onSubmit={save}><div className="formGrid"><label>Contato<select name="lead_id" required defaultValue="" onChange={e=>setSelectedLead(e.target.value)}><option value="">Selecione</option>{leads.map(l=><option key={l.id} value={l.id}>{l.name||"Contato sem nome"}</option>)}</select></label><label>Finalidade<select name="purpose" defaultValue=""><option value="">Qualquer</option><option value="sale">Compra</option><option value="rent">Locação</option></select></label><label>Zona<select name="zone" defaultValue=""><option value="">Qualquer</option><option value="urban">Urbana</option><option value="rural">Rural</option></select></label><label>Uso<select name="segment" defaultValue=""><option value="">Qualquer</option><option value="residential">Residencial</option><option value="commercial">Comercial</option></select></label><label>Preço mínimo<input name="min_price" type="number" min="0" /></label><label>Preço máximo<input name="max_price" type="number" min="0" /></label><label>Quartos mínimos<input name="min_bedrooms" type="number" min="0" /></label><label>Vagas mínimas<input name="min_parking" type="number" min="0" /></label></div><label>Observações<textarea name="notes" rows={3} placeholder="Ex.: aceita financiamento, prefere térrea, precisa de quintal" /></label><div className="formActions"><button className="button primary">Salvar perfil</button></div></form>
  {selectedLead?<div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Imóvel compatível</th><th>Preço</th><th>Aderência</th></tr></thead><tbody>{visible.map(m=><tr key={m.property_id}><td><strong>{m.code}</strong><small className="tableSub">{m.title}</small></td><td>{Number(m.price||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td><td><span className="statusPill">{m.match_score}%</span></td></tr>)}{!visible.length?<tr><td colSpan={3}>Salve as preferências para visualizar os melhores imóveis disponíveis.</td></tr>:null}</tbody></table></div>:null}</>:null}{message?<div className="formMessage">{message}</div>:null}</div>;
}
