"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { getCurrentAgency } from "../lib/currentAgency";
import { isSupabaseConfigured, supabaseBrowser } from "../lib/supabaseBrowser";

type Settings={enabled:boolean;auto_contact:boolean;min_match_score:number;cooldown_hours:number;channels:string[];require_explicit_consent:boolean;notify_broker:boolean;quiet_hours_enabled:boolean;quiet_hours_start:string;quiet_hours_end:string;timezone:string};
type Opportunity={id:string;match_score:number;status:string;channel:string|null;ai_message:string|null;last_error?:string|null;created_at:string;leads?:{name?:string|null;phone?:string|null;email?:string|null}|null;properties?:{code?:string|null;title?:string|null;price?:number|null}|null};
type Usage={used_this_month:number;monthly_limit:number|null;quiet_now:boolean};
type ResponseSummary={responses:number;interested:number;requested_details:number;requested_visit:number;not_interested:number;opt_out:number;responses_this_month:number};
const defaults:Settings={enabled:false,auto_contact:false,min_match_score:80,cooldown_hours:72,channels:["whatsapp"],require_explicit_consent:true,notify_broker:true,quiet_hours_enabled:true,quiet_hours_start:"20:00",quiet_hours_end:"08:00",timezone:"America/Sao_Paulo"};
const statusLabels:Record<string,string>={queued:"Na fila",review:"Em revisão",approved:"Aprovada",sent:"Enviada",skipped:"Ignorada",failed:"Falhou",cancelled:"Cancelada"};
const channelLabels:Record<string,string>={whatsapp:"WhatsApp",email:"E-mail",sms:"SMS"};
const money=(value:number|null|undefined)=>value==null?"Preço não informado":Number(value).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export default function AdminBuyerOutreach(){
  const [agencyId,setAgencyId]=useState(""); const [settings,setSettings]=useState<Settings>(defaults); const [settingsLoaded,setSettingsLoaded]=useState(false); const [items,setItems]=useState<Opportunity[]>([]); const [usage,setUsage]=useState<Usage>({used_this_month:0,monthly_limit:null,quiet_now:false}); const [responses,setResponses]=useState<ResponseSummary>({responses:0,interested:0,requested_details:0,requested_visit:0,not_interested:0,opt_out:0,responses_this_month:0}); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false); const [generating,setGenerating]=useState(""); const [filter,setFilter]=useState("all");
  async function load(){if(!supabaseBrowser||!isSupabaseConfigured)return; const agency=await getCurrentAgency(); if(!agency)return setMessage("Imobiliária ativa não encontrada."); setAgencyId(agency.agencyId); const [s,o,u,r]=await Promise.all([
    supabaseBrowser.from("buyer_outreach_settings").select("enabled,auto_contact,min_match_score,cooldown_hours,channels,require_explicit_consent,notify_broker,quiet_hours_enabled,quiet_hours_start,quiet_hours_end,timezone").eq("agency_id",agency.agencyId).maybeSingle(),
    supabaseBrowser.from("buyer_property_opportunities").select("id,match_score,status,channel,ai_message,last_error,created_at,leads(name,phone,email),properties(code,title,price)").eq("agency_id",agency.agencyId).order("created_at",{ascending:false}).limit(100),
    supabaseBrowser.from("agency_buyer_outreach_usage").select("used_this_month,monthly_limit,quiet_now").eq("agency_id",agency.agencyId).maybeSingle(),
    supabaseBrowser.from("agency_buyer_outreach_response_summary").select("responses,interested,requested_details,requested_visit,not_interested,opt_out,responses_this_month").eq("agency_id",agency.agencyId).maybeSingle(),
  ]); const hardError=[s.error,o.error,u.error,r.error].find(error=>error&&!['42P01','42703'].includes(error.code||'')); if(hardError)setMessage(hardError.message); setSettings(s.data?({...defaults,...s.data} as Settings):defaults); setSettingsLoaded(true); setItems((o.data||[]) as unknown as Opportunity[]); if(u.data)setUsage(u.data as Usage); if(r.data)setResponses(r.data as ResponseSummary);}
  useEffect(()=>{void load();},[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault(); if(!supabaseBrowser||!agencyId)return; const form=new FormData(event.currentTarget); const channels=[form.get("whatsapp")==="on"?"whatsapp":"",form.get("email")==="on"?"email":""].filter(Boolean); if(!channels.length)return setMessage("Selecione pelo menos um canal."); const next:Settings={enabled:form.get("enabled")==="on",auto_contact:form.get("auto_contact")==="on",min_match_score:Math.max(0,Math.min(100,Number(form.get("min_match_score")||80))),cooldown_hours:Math.max(1,Math.min(720,Number(form.get("cooldown_hours")||72))),channels,require_explicit_consent:form.get("require_explicit_consent")==="on",notify_broker:form.get("notify_broker")==="on",quiet_hours_enabled:form.get("quiet_hours_enabled")==="on",quiet_hours_start:String(form.get("quiet_hours_start")||"20:00"),quiet_hours_end:String(form.get("quiet_hours_end")||"08:00"),timezone:String(form.get("timezone")||"America/Sao_Paulo")}; setSaving(true); setMessage(""); const {error}=await supabaseBrowser.from("buyer_outreach_settings").upsert({agency_id:agencyId,...next,updated_at:new Date().toISOString()},{onConflict:"agency_id"}); setSaving(false); if(error)return setMessage(error.message); setSettings(next); setMessage("Configuração de oportunidades salva."); await load();}
  async function changeStatus(id:string,status:string){if(!supabaseBrowser||!agencyId)return; const payload:any={status,updated_at:new Date().toISOString()}; if(status==="approved"){payload.approved_at=new Date().toISOString(); const user=await supabaseBrowser.auth.getUser(); payload.approved_by=user.data.user?.id||null;} if(status==="skipped")payload.skip_reason="Ignorado manualmente"; const {error}=await supabaseBrowser.from("buyer_property_opportunities").update(payload).eq("id",id).eq("agency_id",agencyId); if(error)return setMessage(error.message); await load();}
  async function generateMessage(id:string){if(!supabaseBrowser||!agencyId)return; setGenerating(id); setMessage(""); const {data,error}=await supabaseBrowser.functions.invoke("generate-buyer-opportunity-message",{body:{agency_id:agencyId,opportunity_id:id}}); setGenerating(""); if(error)return setMessage(error.message); if(data?.error)return setMessage(String(data.error)); setMessage("Mensagem preparada pela IA para revisão."); await load();}
  const pending=items.filter(i=>i.status==="queued"||i.status==="review"||i.status==="approved").length;
  const limitText=usage.monthly_limit==null?"Ilimitado":String(usage.monthly_limit);
  const flow={detected:items.length,review:items.filter(i=>i.status==="review"||i.status==="queued").length,approved:items.filter(i=>i.status==="approved").length,sent:items.filter(i=>i.status==="sent").length};
  const positive=responses.interested+responses.requested_details+responses.requested_visit;
  const responseRate=flow.sent?Math.round((responses.responses/flow.sent)*100):0;
  const interestRate=responses.responses?Math.round((positive/responses.responses)*100):0;
  const visible=useMemo(()=>filter==="all"?items:items.filter(item=>item.status===filter),[items,filter]);
  const formKey=settingsLoaded?JSON.stringify(settings):"loading";
  return <div className="adminPanel adminOnly" id="oportunidades-ia"><div className="adminPanelHeader"><div><span className="eyebrow">IA COMERCIAL</span><h2>Oportunidades automáticas para compradores</h2><p>Detecta imóveis compatíveis e organiza o contato sem ultrapassar consentimento, plano, intervalo mínimo ou horário silencioso.</p></div><span>{pending} pendente(s)</span></div>
  <div className="statsGrid"><article><strong>{usage.used_this_month}/{limitText}</strong><span>contatos no mês</span></article><article><strong>{responses.responses_this_month}</strong><span>respostas no mês</span></article><article><strong>{responseRate}%</strong><span>taxa de resposta</span></article><article><strong>{interestRate}%</strong><span>interesse nas respostas</span></article></div>
  <div className="statsGrid"><article><strong>{positive}</strong><span>sinais de interesse</span></article><article><strong>{responses.requested_visit}</strong><span>pedidos de visita</span></article><article><strong>{responses.opt_out}</strong><span>descadastros</span></article><article><strong>{usage.quiet_now?"Ativo":"Livre"}</strong><span>horário silencioso</span></article></div>
  <div className="adminPanelHeader"><div><span className="eyebrow">FLUXO VISUAL</span><h3>Da compatibilidade ao contato</h3><p>Acompanhe rapidamente em que etapa estão as oportunidades encontradas pela IA.</p></div></div>
  <div className="statsGrid"><article><strong>{flow.detected}</strong><span>1. Detectadas</span></article><article><strong>{flow.review}</strong><span>2. Em revisão</span></article><article><strong>{flow.approved}</strong><span>3. Aprovadas</span></article><article><strong>{flow.sent}</strong><span>4. Enviadas</span></article></div>
  <div className="formNotice"><strong>Proteção do comprador:</strong> nenhum envio automático é realizado sem consentimento ativo para alertas e autorização do canal escolhido. Aprovar uma oportunidade não contorna essa regra.</div>
  {settingsLoaded?<form key={formKey} className="propertyForm" onSubmit={save}><div className="formGrid three"><label>Pontuação mínima<input name="min_match_score" type="number" min="0" max="100" defaultValue={settings.min_match_score}/></label><label>Intervalo mínimo (horas)<input name="cooldown_hours" type="number" min="1" max="720" defaultValue={settings.cooldown_hours}/></label><label className="checkLabel"><input name="enabled" type="checkbox" defaultChecked={settings.enabled}/> Ativar detecção de oportunidades</label></div>
  <div className="formGrid"><label className="checkLabel"><input name="whatsapp" type="checkbox" defaultChecked={settings.channels.includes("whatsapp")}/> WhatsApp</label><label className="checkLabel"><input name="email" type="checkbox" defaultChecked={settings.channels.includes("email")}/> E-mail</label></div>
  <div className="formGrid three"><label className="checkLabel"><input name="quiet_hours_enabled" type="checkbox" defaultChecked={settings.quiet_hours_enabled}/> Usar horário silencioso</label><label>Não enviar após<input name="quiet_hours_start" type="time" defaultValue={settings.quiet_hours_start?.slice(0,5)||"20:00"}/></label><label>Retomar a partir de<input name="quiet_hours_end" type="time" defaultValue={settings.quiet_hours_end?.slice(0,5)||"08:00"}/></label></div>
  <label>Fuso horário<input name="timezone" defaultValue={settings.timezone||"America/Sao_Paulo"}/></label>
  <div className="formGrid"><label className="checkLabel"><input name="require_explicit_consent" type="checkbox" defaultChecked={settings.require_explicit_consent}/> Sem consentimento, manter oportunidade em revisão</label><label className="checkLabel"><input name="notify_broker" type="checkbox" defaultChecked={settings.notify_broker}/> Avisar corretor responsável</label><label className="checkLabel"><input name="auto_contact" type="checkbox" defaultChecked={settings.auto_contact}/> Processar automaticamente oportunidades autorizadas</label></div>
  <div className="formActions"><button type="submit" className="button primary" disabled={saving}>{saving?"Salvando...":"Salvar configuração"}</button></div></form>:null}
  {message?<div className="formMessage">{message}</div>:null}
  <div className="adminFilters"><label>Situação<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas</option><option value="queued">Na fila</option><option value="review">Em revisão</option><option value="approved">Aprovadas</option><option value="sent">Enviadas</option><option value="failed">Falhas</option><option value="skipped">Ignoradas</option></select></label></div>
  <div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Comprador</th><th>Imóvel</th><th>Match</th><th>Canal</th><th>Situação</th><th>Mensagem</th><th>Ações</th></tr></thead><tbody>{visible.length?visible.map(item=><tr key={item.id}><td><strong>{item.leads?.name||"Contato sem nome"}</strong><small className="tableSub">{item.leads?.phone||item.leads?.email||"sem canal"}</small></td><td><strong>{item.properties?.code||"—"}</strong><small className="tableSub">{item.properties?.title||"Imóvel"} · {money(item.properties?.price)}</small></td><td><span className="statusPill">{item.match_score}%</span></td><td>{item.channel?channelLabels[item.channel]||item.channel:"Revisar"}</td><td><span className="statusPill">{statusLabels[item.status]||item.status}</span>{item.last_error?<small className="tableSub">{item.last_error}</small>:null}</td><td>{item.ai_message?<details><summary>Ver texto</summary><small className="tableSub">{item.ai_message}</small></details>:<span>—</span>}</td><td><div className="accessActions">{item.status!=="sent"?<button type="button" className="miniButton" onClick={()=>void generateMessage(item.id)} disabled={generating===item.id}>{generating===item.id?"Gerando...":"Gerar texto"}</button>:null}{item.status!=="sent"&&item.status!=="approved"?<button type="button" className="miniButton" onClick={()=>void changeStatus(item.id,"approved")}>Aprovar</button>:null}{item.status!=="sent"&&item.status!=="skipped"?<button type="button" className="miniButton muted" onClick={()=>void changeStatus(item.id,"skipped")}>Ignorar</button>:null}</div></td></tr>):<tr><td colSpan={7}>Nenhuma oportunidade nesta situação.</td></tr>}</tbody></table></div>
  <div className="formMessage">Respostas, pedidos de informações, pedidos de visita e descadastros entram no CRM quando o provedor envia os eventos ao webhook da plataforma.</div></div>;
}
