"use client";

import { useEffect, useState } from "react";
import { getCurrentAgency } from "../lib/currentAgency";
import { isSupabaseConfigured, supabaseBrowser } from "../lib/supabaseBrowser";

type Property={id:string;code:string;title:string}; type Item={id:string;property_id:string;label:string;status:string;expires_at:string|null;notes:string|null};
const statusLabels:Record<string,string>={pending:"Pendente",received:"Recebido",approved:"Aprovado",rejected:"Rejeitado",not_applicable:"Não se aplica"};
export default function AdminPropertyDocumentChecklist(){const [agencyId,setAgencyId]=useState("");const [properties,setProperties]=useState<Property[]>([]);const [propertyId,setPropertyId]=useState("");const [items,setItems]=useState<Item[]>([]);const [message,setMessage]=useState("");
async function loadBase(){if(!supabaseBrowser||!isSupabaseConfigured)return;const a=await getCurrentAgency();if(!a)return setMessage("Imobiliária ativa não encontrada.");setAgencyId(a.agencyId);const r=await supabaseBrowser.from("properties").select("id,code,title").eq("agency_id",a.agencyId).order("updated_at",{ascending:false}).limit(150);if(r.error)return setMessage(r.error.message);setProperties((r.data||[]) as Property[]);} useEffect(()=>{void loadBase();},[]);
async function loadItems(id:string){setPropertyId(id);setItems([]);if(!supabaseBrowser||!id)return;await supabaseBrowser.rpc("ensure_default_property_document_items",{p_property_id:id});const r=await supabaseBrowser.from("property_document_items").select("id,property_id,label,status,expires_at,notes").eq("agency_id",agencyId).eq("property_id",id).order("created_at");if(r.error)return setMessage(r.error.message);setItems((r.data||[]) as Item[]);}
async function update(item:Item,patch:Partial<Item>){if(!supabaseBrowser)return;const r=await supabaseBrowser.from("property_document_items").update(patch).eq("id",item.id).eq("agency_id",agencyId);if(r.error)return setMessage(r.error.message);setItems(c=>c.map(x=>x.id===item.id?{...x,...patch}:x));}
return <div className="adminPanel" id="documentacao-imovel"><div className="adminPanelHeader"><div><span className="eyebrow">DOCUMENTAÇÃO DO IMÓVEL</span><h2>Checklist documental</h2><p>Controle matrícula, IPTU, documentos do proprietário, ônus e demais itens antes da negociação.</p></div><span>{items.filter(i=>i.status==='approved').length}/{items.length||0} aprovados</span></div>{isSupabaseConfigured?<><div className="adminFilters"><select value={propertyId} onChange={e=>void loadItems(e.target.value)}><option value="">Selecione o imóvel</option>{properties.map(p=><option key={p.id} value={p.id}>{p.code} · {p.title}</option>)}</select></div>{propertyId?<div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Documento</th><th>Status</th><th>Validade</th><th>Observação</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><strong>{i.label}</strong></td><td><select value={i.status} onChange={e=>void update(i,{status:e.target.value})}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td><input type="date" value={i.expires_at||""} onChange={e=>void update(i,{expires_at:e.target.value||null})}/></td><td><input value={i.notes||""} onBlur={e=>void update(i,{notes:e.target.value||null})} onChange={e=>setItems(c=>c.map(x=>x.id===i.id?{...x,notes:e.target.value}:x))} placeholder="Observação"/></td></tr>)}</tbody></table></div>:null}</>:null}{message?<div className="formMessage">{message}</div>:null}</div>}
