"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import { getCurrentAgency } from "../lib/currentAgency";
import { isSupabaseConfigured,supabaseBrowser } from "../lib/supabaseBrowser";

type Lead={id:string;name:string|null;property_id:string|null;broker_id:string|null};
type Property={id:string;code:string;title:string};
type Broker={id:string;name:string};
type Visit={id:string;lead_id:string;property_id:string|null;broker_id:string|null;scheduled_at:string;duration_minutes:number;status:"scheduled"|"completed"|"cancelled"|"no_show";notes:string|null};
const labels={scheduled:"Agendada",completed:"Concluída",cancelled:"Cancelada",no_show:"Não compareceu"} as const;

export default function AdminVisitSchedule(){
 const [agencyId,setAgencyId]=useState("");const [leads,setLeads]=useState<Lead[]>([]);const [properties,setProperties]=useState<Property[]>([]);const [brokers,setBrokers]=useState<Broker[]>([]);const [visits,setVisits]=useState<Visit[]>([]);const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);const [selectedLeadId,setSelectedLeadId]=useState("");
 async function load(){if(!supabaseBrowser||!isSupabaseConfigured)return;const agency=await getCurrentAgency();if(!agency)return setMessage("Imobiliária ativa não encontrada.");setAgencyId(agency.agencyId);const [l,p,b,v]=await Promise.all([
  supabaseBrowser.from("leads").select("id,name,property_id,broker_id").eq("agency_id",agency.agencyId).order("created_at",{ascending:false}).limit(150),
  supabaseBrowser.from("properties").select("id,code,title").eq("agency_id",agency.agencyId).neq("status","inactive").order("updated_at",{ascending:false}).limit(200),
  supabaseBrowser.from("brokers").select("id,name").eq("agency_id",agency.agencyId).eq("active",true).order("name"),
  supabaseBrowser.from("property_visit_appointments").select("id,lead_id,property_id,broker_id,scheduled_at,duration_minutes,status,notes").eq("agency_id",agency.agencyId).order("scheduled_at",{ascending:true}).limit(150)
 ]);const error=[l.error,p.error,b.error,v.error].find(Boolean);if(error&&!['42P01','42703'].includes(error.code||''))setMessage(error.message);setLeads((l.data||[]) as Lead[]);setProperties((p.data||[]) as Property[]);setBrokers((b.data||[]) as Broker[]);setVisits((v.data||[]) as Visit[]);}
 useEffect(()=>{void load();},[]);
 const selectedLead=useMemo(()=>leads.find(x=>x.id===selectedLeadId)||null,[leads,selectedLeadId]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabaseBrowser||!agencyId)return;const form=e.currentTarget;const f=new FormData(form);const leadId=String(f.get("lead_id")||"");const when=String(f.get("scheduled_at")||"");if(!leadId||!when)return setMessage("Selecione o contato e a data da visita.");const lead=leads.find(x=>x.id===leadId);const propertyId=String(f.get("property_id")||"")||lead?.property_id||null;const brokerId=String(f.get("broker_id")||"")||lead?.broker_id||null;if(!propertyId)return setMessage("Selecione um imóvel para a visita.");if(!brokerId)return setMessage("Selecione um corretor responsável pela visita.");setSaving(true);setMessage("");const result=await supabaseBrowser.from("property_visit_appointments").insert({agency_id:agencyId,lead_id:leadId,property_id:propertyId,broker_id:brokerId,scheduled_at:new Date(when).toISOString(),duration_minutes:Number(f.get("duration_minutes")||60),notes:String(f.get("notes")||"").trim()||null});if(result.error){setSaving(false);return setMessage(result.error.message);}const leadUpdate=await supabaseBrowser.from("leads").update({status:"visit_scheduled"}).eq("id",leadId).eq("agency_id",agencyId);setSaving(false);if(leadUpdate.error)return setMessage(`Visita criada, mas não foi possível atualizar o funil do contato: ${leadUpdate.error.message}`);form.reset();setSelectedLeadId("");setMessage("Visita agendada e contato movido para visita agendada.");await load();}
 async function setStatus(id:string,status:Visit["status"]){if(!supabaseBrowser||!agencyId)return;setMessage("");const result=await supabaseBrowser.from("property_visit_appointments").update({status}).eq("id",id).eq("agency_id",agencyId);if(result.error)return setMessage(result.error.message);setMessage(`Visita marcada como ${labels[status].toLowerCase()}.`);await load();}
 const leadName=(id:string)=>leads.find(x=>x.id===id)?.name||"Contato";const propertyName=(id:string|null)=>id?properties.find(x=>x.id===id)?.code||"Imóvel":"—";const brokerName=(id:string|null)=>id?brokers.find(x=>x.id===id)?.name||"Corretor":"—";
 const upcoming=visits.filter(v=>v.status==='scheduled'&&new Date(v.scheduled_at).getTime()>=Date.now());
 const today=visits.filter(v=>v.status==='scheduled'&&new Date(v.scheduled_at).toDateString()===new Date().toDateString()).length;
 const completedMonth=visits.filter(v=>v.status==='completed'&&new Date(v.scheduled_at).getMonth()===new Date().getMonth()&&new Date(v.scheduled_at).getFullYear()===new Date().getFullYear()).length;
 return <div className="adminPanel" id="agenda-visitas"><div className="adminPanelHeader"><div><span className="eyebrow">AGENDA</span><h2>Visitas aos imóveis</h2><p>Agende visitas, associe corretor e imóvel e acompanhe conclusão, cancelamento ou ausência.</p></div><span>{upcoming.length} próxima(s)</span></div>
 <div className="adminMetrics planMetrics"><article><span>Próximas</span><strong>{upcoming.length}</strong></article><article><span>Hoje</span><strong>{today}</strong></article><article><span>Concluídas no mês</span><strong>{completedMonth}</strong></article></div>
 <form className="propertyForm" onSubmit={create}><div className="formGrid"><label>Contato<select name="lead_id" required value={selectedLeadId} onChange={e=>setSelectedLeadId(e.target.value)}><option value="">Selecione</option>{leads.map(x=><option key={x.id} value={x.id}>{x.name||"Contato sem nome"}</option>)}</select></label><label>Data e hora<input name="scheduled_at" type="datetime-local" required /></label><label>Imóvel<select name="property_id" defaultValue=""><option value="">{selectedLead?.property_id?`Usar ${propertyName(selectedLead.property_id)}`:"Selecione um imóvel"}</option>{properties.map(x=><option key={x.id} value={x.id}>{x.code} · {x.title}</option>)}</select></label><label>Corretor<select name="broker_id" defaultValue=""><option value="">{selectedLead?.broker_id?`Usar ${brokerName(selectedLead.broker_id)}`:"Selecione um corretor"}</option>{brokers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Duração<select name="duration_minutes" defaultValue="60"><option value="30">30 min</option><option value="45">45 min</option><option value="60">1 hora</option><option value="90">1h30</option><option value="120">2 horas</option></select></label></div><label>Observações<textarea name="notes" rows={2}/></label><button className="button primary" disabled={saving}>{saving?"Salvando...":"Agendar visita"}</button></form>
 <div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Data</th><th>Contato</th><th>Imóvel</th><th>Corretor</th><th>Status</th><th>Ações</th></tr></thead><tbody>{visits.map(v=><tr key={v.id}><td>{new Date(v.scheduled_at).toLocaleString('pt-BR')}</td><td>{leadName(v.lead_id)}</td><td>{propertyName(v.property_id)}</td><td>{brokerName(v.broker_id)}</td><td><span className="statusPill">{labels[v.status]}</span></td><td>{v.status==='scheduled'?<div className="adminActions"><button className="miniButton" type="button" onClick={()=>void setStatus(v.id,'completed')}>Concluir</button><button className="miniButton" type="button" onClick={()=>void setStatus(v.id,'no_show')}>Não compareceu</button><button className="miniButton" type="button" onClick={()=>void setStatus(v.id,'cancelled')}>Cancelar</button></div>:null}</td></tr>)}</tbody></table></div>{message?<div className="formMessage">{message}</div>:null}</div>;
}
