"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import { getCurrentAgency } from "../lib/currentAgency";
import { isSupabaseConfigured,supabaseBrowser } from "../lib/supabaseBrowser";

type Lead={id:string;name:string|null};
type City={id:string;name:string;state_code:string};
type Neighborhood={id:string;city_id:string;name:string};
type PropertyType={id:string;name:string};
type Match={lead_id:string;property_id:string;code:string;title:string;price:number|null;match_score:number;matched_weight:number;total_weight:number};
type Preference={purpose:string;zone:string;segment:string;city_id:string;neighborhood_id:string;property_type_id:string;min_price:string;max_price:string;min_bedrooms:string;min_parking:string;notes:string};
const emptyPreference:Preference={purpose:"",zone:"",segment:"",city_id:"",neighborhood_id:"",property_type_id:"",min_price:"",max_price:"",min_bedrooms:"",min_parking:"",notes:""};

export default function AdminBuyerPreferences(){
  const [agencyId,setAgencyId]=useState("");const [leads,setLeads]=useState<Lead[]>([]);const [cities,setCities]=useState<City[]>([]);const [neighborhoods,setNeighborhoods]=useState<Neighborhood[]>([]);const [types,setTypes]=useState<PropertyType[]>([]);const [matches,setMatches]=useState<Match[]>([]);const [selectedLead,setSelectedLead]=useState("");const [pref,setPref]=useState<Preference>(emptyPreference);const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);const [loadingMatches,setLoadingMatches]=useState(false);

  async function loadBase(){if(!supabaseBrowser||!isSupabaseConfigured)return;const agency=await getCurrentAgency();if(!agency)return setMessage("Imobiliária ativa não encontrada.");setAgencyId(agency.agencyId);const [leadResult,cityResult,neighborhoodResult,typeResult]=await Promise.all([
    supabaseBrowser.from("leads").select("id,name").eq("agency_id",agency.agencyId).order("created_at",{ascending:false}).limit(250),
    supabaseBrowser.from("cities").select("id,name,state_code").order("state_code").order("name"),
    supabaseBrowser.from("neighborhoods").select("id,city_id,name").order("name"),
    supabaseBrowser.from("property_types").select("id,name").eq("active",true).order("name")
  ]);const error=[leadResult.error,cityResult.error,neighborhoodResult.error,typeResult.error].find(Boolean);if(error&&!['42P01','42703'].includes(error.code||''))setMessage(error.message);setLeads((leadResult.data||[]) as Lead[]);setCities((cityResult.data||[]) as City[]);setNeighborhoods((neighborhoodResult.data||[]) as Neighborhood[]);setTypes((typeResult.data||[]) as PropertyType[]);}
  useEffect(()=>{void loadBase();},[]);

  async function loadLead(leadId:string){setSelectedLead(leadId);setMatches([]);setMessage("");if(!supabaseBrowser||!agencyId||!leadId){setPref(emptyPreference);return;}setLoadingMatches(true);const [preferenceResult,matchResult]=await Promise.all([
    supabaseBrowser.from("lead_property_preferences").select("purpose,zone,segment,city_id,neighborhood_id,property_type_id,min_price,max_price,min_bedrooms,min_parking,notes").eq("agency_id",agencyId).eq("lead_id",leadId).maybeSingle(),
    supabaseBrowser.from("lead_property_match_candidates").select("lead_id,property_id,code,title,price,match_score,matched_weight,total_weight").eq("agency_id",agencyId).eq("lead_id",leadId).order("match_score",{ascending:false}).limit(30)
  ]);setLoadingMatches(false);if(preferenceResult.error&&!['PGRST116','42P01'].includes(preferenceResult.error.code||''))setMessage(preferenceResult.error.message);if(matchResult.error&&!['42P01','42703'].includes(matchResult.error.code||''))setMessage(matchResult.error.message);const p=preferenceResult.data as Record<string,unknown>|null;setPref(p?{purpose:String(p.purpose||""),zone:String(p.zone||""),segment:String(p.segment||""),city_id:String(p.city_id||""),neighborhood_id:String(p.neighborhood_id||""),property_type_id:String(p.property_type_id||""),min_price:p.min_price==null?"":String(p.min_price),max_price:p.max_price==null?"":String(p.max_price),min_bedrooms:p.min_bedrooms==null?"":String(p.min_bedrooms),min_parking:p.min_parking==null?"":String(p.min_parking),notes:String(p.notes||"")}:emptyPreference);setMatches((matchResult.data||[]) as Match[]);}

  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabaseBrowser||!agencyId||!selectedLead)return setMessage("Selecione o contato.");if(pref.min_price&&pref.max_price&&Number(pref.min_price)>Number(pref.max_price))return setMessage("O preço mínimo não pode ser maior que o preço máximo.");setSaving(true);setMessage("");const payload={agency_id:agencyId,lead_id:selectedLead,purpose:pref.purpose||null,zone:pref.zone||null,segment:pref.segment||null,city_id:pref.city_id||null,neighborhood_id:pref.neighborhood_id||null,property_type_id:pref.property_type_id||null,min_price:pref.min_price===""?null:Number(pref.min_price),max_price:pref.max_price===""?null:Number(pref.max_price),min_bedrooms:pref.min_bedrooms===""?null:Number(pref.min_bedrooms),min_parking:pref.min_parking===""?null:Number(pref.min_parking),notes:pref.notes.trim()||null,active:true};const r=await supabaseBrowser.from("lead_property_preferences").upsert(payload,{onConflict:"agency_id,lead_id"});setSaving(false);if(r.error)return setMessage(r.error.message);setMessage("Preferências salvas e aderência recalculada.");await loadLead(selectedLead);}

  const cityNeighborhoods=useMemo(()=>pref.city_id?neighborhoods.filter(n=>n.city_id===pref.city_id):neighborhoods,[neighborhoods,pref.city_id]);
  const strongMatches=matches.filter(m=>m.match_score>=80).length;
  const field=(key:keyof Preference,value:string)=>setPref(current=>({...current,[key]:value,...(key==='city_id'?{neighborhood_id:""}:{})}));

  return <div className="adminPanel" id="perfil-compra"><div className="adminPanelHeader"><div><span className="eyebrow">MATCH COMERCIAL</span><h2>Perfil de compra</h2><p>Registre o que o cliente procura e veja os imóveis disponíveis com aderência calculada somente sobre os critérios realmente informados.</p></div><span>{selectedLead?`${matches.length} compatível(is)`:isSupabaseConfigured?`${leads.length} contato(s)`:"Modo demonstração"}</span></div>
  {selectedLead?<div className="adminMetrics planMetrics"><article><span>Imóveis analisados</span><strong>{matches.length}</strong></article><article><span>Aderência ≥ 80%</span><strong>{strongMatches}</strong></article><article><span>Melhor aderência</span><strong>{matches[0]?`${matches[0].match_score}%`:"—"}</strong></article></div>:null}
  {isSupabaseConfigured?<><form className="propertyForm" onSubmit={save}><div className="formGrid"><label>Contato<select required value={selectedLead} onChange={e=>void loadLead(e.target.value)}><option value="">Selecione</option>{leads.map(l=><option key={l.id} value={l.id}>{l.name||"Contato sem nome"}</option>)}</select></label><label>Finalidade<select value={pref.purpose} onChange={e=>field('purpose',e.target.value)}><option value="">Qualquer</option><option value="sale">Compra</option><option value="rent">Locação</option></select></label><label>Zona<select value={pref.zone} onChange={e=>field('zone',e.target.value)}><option value="">Qualquer</option><option value="urban">Urbana</option><option value="rural">Rural</option></select></label><label>Uso<select value={pref.segment} onChange={e=>field('segment',e.target.value)}><option value="">Qualquer</option><option value="residential">Residencial</option><option value="commercial">Comercial</option></select></label><label>Cidade<select value={pref.city_id} onChange={e=>field('city_id',e.target.value)}><option value="">Qualquer</option>{cities.map(c=><option key={c.id} value={c.id}>{c.name} - {c.state_code}</option>)}</select></label><label>Bairro<select value={pref.neighborhood_id} onChange={e=>field('neighborhood_id',e.target.value)} disabled={!pref.city_id}><option value="">Qualquer</option>{cityNeighborhoods.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label>Tipo de imóvel<select value={pref.property_type_id} onChange={e=>field('property_type_id',e.target.value)}><option value="">Qualquer</option>{types.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Preço mínimo<input value={pref.min_price} onChange={e=>field('min_price',e.target.value)} type="number" min="0" /></label><label>Preço máximo<input value={pref.max_price} onChange={e=>field('max_price',e.target.value)} type="number" min="0" /></label><label>Quartos mínimos<input value={pref.min_bedrooms} onChange={e=>field('min_bedrooms',e.target.value)} type="number" min="0" /></label><label>Vagas mínimas<input value={pref.min_parking} onChange={e=>field('min_parking',e.target.value)} type="number" min="0" /></label></div><label>Observações<textarea value={pref.notes} onChange={e=>field('notes',e.target.value)} rows={3} placeholder="Ex.: aceita financiamento, prefere térrea, precisa de quintal" /></label><div className="formActions"><button className="button primary" disabled={saving||!selectedLead}>{saving?"Salvando...":"Salvar perfil"}</button></div></form>
  {selectedLead?<div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Imóvel compatível</th><th>Preço</th><th>Aderência</th></tr></thead><tbody>{matches.slice(0,10).map(m=><tr key={m.property_id}><td><strong>{m.code}</strong><small className="tableSub">{m.title}</small></td><td>{m.price==null?"Consulte":Number(m.price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td><td><span className="statusPill">{m.match_score}%</span></td></tr>)}{!matches.length?<tr><td colSpan={3}>{loadingMatches?"Calculando aderência...":"Salve critérios para visualizar os melhores imóveis disponíveis."}</td></tr>:null}</tbody></table></div>:null}</>:null}{message?<div className="formMessage">{message}</div>:null}</div>;
}
