"use client";

import { FormEvent, useEffect, useState } from "react";
import { getCurrentAgency } from "../lib/currentAgency";
import { isSupabaseConfigured, supabaseBrowser } from "../lib/supabaseBrowser";

type Broker={id:string;name:string}; type Goal={broker_id:string;month:string;leads_goal:number;visits_goal:number;won_goal:number;new_properties_goal:number;leads_done:number;visits_done:number;won_done:number;new_properties_done:number};
export default function AdminBrokerGoals(){const [agencyId,setAgencyId]=useState("");const [brokers,setBrokers]=useState<Broker[]>([]);const [goals,setGoals]=useState<Goal[]>([]);const [message,setMessage]=useState("");
async function load(){if(!supabaseBrowser||!isSupabaseConfigured)return;const a=await getCurrentAgency();if(!a)return setMessage("Imobiliária ativa não encontrada.");setAgencyId(a.agencyId);const [b,g]=await Promise.all([supabaseBrowser.from("brokers").select("id,name").eq("agency_id",a.agencyId).eq("active",true).order("name"),supabaseBrowser.from("broker_monthly_goal_progress").select("broker_id,month,leads_goal,visits_goal,won_goal,new_properties_goal,leads_done,visits_done,won_done,new_properties_done").eq("agency_id",a.agencyId).order("month",{ascending:false}).limit(60)]);if(b.error&&!['42P01'].includes(b.error.code||''))return setMessage(b.error.message);setBrokers((b.data||[]) as Broker[]);setGoals((g.data||[]) as Goal[]);}useEffect(()=>{void load();},[]);
async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabaseBrowser||!agencyId)return;const f=new FormData(e.currentTarget);const month=String(f.get("month")||"");const broker_id=String(f.get("broker_id")||"");if(!broker_id||!month)return setMessage("Informe corretor e mês.");const payload={agency_id:agencyId,broker_id,month:`${month}-01`,leads_goal:Number(f.get("leads_goal")||0),visits_goal:Number(f.get("visits_goal")||0),won_goal:Number(f.get("won_goal")||0),new_properties_goal:Number(f.get("new_properties_goal")||0)};const r=await supabaseBrowser.from("broker_monthly_goals").upsert(payload,{onConflict:"agency_id,broker_id,month"});if(r.error)return setMessage(r.error.message);setMessage("Meta mensal salva.");await load();}
const brokerName=(id:string)=>brokers.find(b=>b.id===id)?.name||"Corretor";const pct=(done:number,goal:number)=>goal?Math.min(100,Math.round(done*100/goal)):0;
return <div className="adminPanel" id="metas-corretores"><div className="adminPanelHeader"><div><span className="eyebrow">GESTÃO COMERCIAL</span><h2>Metas dos corretores</h2><p>Defina objetivos mensais de leads, visitas, fechamentos e novos imóveis.</p></div><span>{goals.length} meta(s)</span></div>{isSupabaseConfigured?<><form className="propertyForm" onSubmit={save}><div className="formGrid"><label>Corretor<select name="broker_id" required defaultValue=""><option value="">Selecione</option>{brokers.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Mês<input name="month" type="month" required /></label><label>Meta de leads<input name="leads_goal" type="number" min="0" defaultValue="0"/></label><label>Meta de visitas<input name="visits_goal" type="number" min="0" defaultValue="0"/></label><label>Meta de fechamentos<input name="won_goal" type="number" min="0" defaultValue="0"/></label><label>Meta de novos imóveis<input name="new_properties_goal" type="number" min="0" defaultValue="0"/></label></div><div className="formActions"><button className="button primary">Salvar meta</button></div></form><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Corretor / mês</th><th>Leads</th><th>Visitas</th><th>Fechamentos</th><th>Imóveis</th></tr></thead><tbody>{goals.map((g,i)=><tr key={`${g.broker_id}-${g.month}-${i}`}><td><strong>{brokerName(g.broker_id)}</strong><small className="tableSub">{new Date(`${g.month}T12:00:00`).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</small></td><td>{g.leads_done}/{g.leads_goal} <small>({pct(g.leads_done,g.leads_goal)}%)</small></td><td>{g.visits_done}/{g.visits_goal} <small>({pct(g.visits_done,g.visits_goal)}%)</small></td><td>{g.won_done}/{g.won_goal} <small>({pct(g.won_done,g.won_goal)}%)</small></td><td>{g.new_properties_done}/{g.new_properties_goal} <small>({pct(g.new_properties_done,g.new_properties_goal)}%)</small></td></tr>)}{!goals.length?<tr><td colSpan={5}>Nenhuma meta mensal cadastrada.</td></tr>:null}</tbody></table></div></>:null}{message?<div className="formMessage">{message}</div>:null}</div>}
