"use client";

import { useEffect, useMemo, useState } from "react";
import { getCurrentAgency } from "../lib/currentAgency";
import { supabaseBrowser } from "../lib/supabaseBrowser";

type Plan = { id:string; code:string; name:string; description:string|null; monthly_price:number|null; annual_price:number|null; implementation_fee:number|null; annual_discount_percent:number|null; features:Record<string,unknown>|null; display_order:number };
type Subscription = { plan_id:string; status:string; ends_at:string|null };
type Discount = { plan_id:string; billing_cycle:"monthly"|"annual"; final_amount:number; discount_percent:number };
function money(value:number|null|undefined){return value==null?"Valor não definido":new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value));}

export default function MobilePlanActions({ showCurrent = true }: { showCurrent?: boolean }) {
 const [agencyId,setAgencyId]=useState("");const [plans,setPlans]=useState<Plan[]>([]);const [subscription,setSubscription]=useState<Subscription|null>(null);const [discounts,setDiscounts]=useState<Discount[]>([]);const [selectedId,setSelectedId]=useState("");const [cycle,setCycle]=useState<"monthly"|"annual">("monthly");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{if(!supabaseBrowser)return;void(async()=>{const agency=await getCurrentAgency();if(!agency)return;setAgencyId(agency.agencyId);const[p,s,d]=await Promise.all([supabaseBrowser.from("subscription_plans").select("id,code,name,description,monthly_price,annual_price,implementation_fee,annual_discount_percent,features,display_order").eq("active",true).order("display_order").order("name"),supabaseBrowser.from("agency_subscriptions").select("plan_id,status,ends_at").eq("agency_id",agency.agencyId).order("starts_at",{ascending:false}).limit(1).maybeSingle(),supabaseBrowser.rpc("agency_billing_discount_snapshot",{p_agency_id:agency.agencyId})]);if(p.error)return setMessage("Não foi possível carregar os planos agora.");setPlans(((p.data||[]) as Plan[]).filter(plan=>String(plan.features?.internal_only||"false").toLowerCase()!=="true"));setSubscription((s.data||null) as Subscription|null);if(!d.error&&Array.isArray(d.data))setDiscounts(d.data as Discount[]);})();},[]);
 const otherPlans=useMemo(()=>plans.filter(p=>p.id!==subscription?.plan_id),[plans,subscription]);const current=useMemo(()=>plans.find(p=>p.id===subscription?.plan_id)||null,[plans,subscription]);const selected=useMemo(()=>plans.find(p=>p.id===selectedId)||null,[plans,selectedId]);
 function effectivePrice(plan:Plan|null,billingCycle:"monthly"|"annual"){if(!plan)return null;const discount=discounts.find(d=>d.plan_id===plan.id&&d.billing_cycle===billingCycle);return discount?Number(discount.final_amount):Number(billingCycle==="annual"?plan.annual_price:plan.monthly_price);}
 const price=effectivePrice(selected,cycle);const selectedDiscount=selected?discounts.find(d=>d.plan_id===selected.id&&d.billing_cycle===cycle):null;const currentMonthly=effectivePrice(current,"monthly");
 async function checkout(planId:string,billingCycle:"monthly"|"annual"){if(!supabaseBrowser||!agencyId)return;setBusy(true);setMessage("");const returnPath=typeof window!=="undefined"&&window.location.pathname.includes("/app")?"/app/":"/admin/";const result=await supabaseBrowser.functions.invoke("create-infinitepay-checkout",{body:{agency_id:agencyId,plan_id:planId,billing_cycle:billingCycle,return_path:returnPath}});setBusy(false);if(result.error||result.data?.error)return setMessage("Não foi possível iniciar o pagamento agora.");const url=String(result.data?.checkout_url||"");if(!url)return setMessage("O pagamento não retornou um endereço válido.");window.location.assign(url);}
 return <div className="mobilePlanActions">
  {current&&showCurrent?<section className="mobileCurrentPlan"><span>PLANO ATUAL</span><strong>{current.name}</strong><small>{current.description||"Assinatura atual"}{subscription?.ends_at?` · válida até ${new Date(subscription.ends_at).toLocaleDateString("pt-BR")}`:""}</small><button type="button" onClick={()=>void checkout(current.id,"monthly")} disabled={busy||currentMonthly==null||currentMonthly<=0}>{busy?"Aguarde...":`Renovar mensal · ${money(currentMonthly)}`}</button></section>:current?<div className="mobileRenewRow"><strong>{money(currentMonthly)}</strong><button type="button" onClick={()=>void checkout(current.id,"monthly")} disabled={busy||currentMonthly==null||currentMonthly<=0}>{busy?"Aguarde...":"Renovar com InfinitePay"}</button></div>:null}
  <details className="mobileUpgradeBox"><summary><strong>Upgrade / alterar plano</strong><span>+</span></summary><div className="mobileUpgradeBody"><div className="mobilePlanChoices">{otherPlans.map(plan=><button type="button" key={plan.id} className={selectedId===plan.id?"active":""} onClick={()=>setSelectedId(plan.id)}><strong>{plan.name}</strong><small>{money(plan.monthly_price)}/mês</small></button>)}</div>{selected?<div className="mobileSelectedPlan"><strong>{selected.name}</strong><p>{selected.description||"Plano disponível para sua imobiliária."}</p><label>Cobrança<select value={cycle} onChange={e=>setCycle(e.target.value as "monthly"|"annual")}><option value="monthly">Mensal</option><option value="annual">Anual · 25% OFF</option></select></label><div className="mobileSelectedPrice">{money(price)}</div>{cycle==="annual"?<small>🎁 Implantação grátis no anual.</small>:null}{selectedDiscount?<small>Desconto especial adicional: {Number(selectedDiscount.discount_percent).toLocaleString("pt-BR",{maximumFractionDigits:2})}%.</small>:null}<button type="button" onClick={()=>void checkout(selected.id,cycle)} disabled={busy||price==null||Number(price)<=0}>{busy?"Aguarde...":`Escolher ${selected.name}`}</button></div>:null}</div></details>
  {message?<div className="formMessage">{message}</div>:null}
 </div>;
}
