"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabaseBrowser } from "../lib/supabaseBrowser";

type CouponRow={id:string;code:string;discount_type:"percent"|"fixed";discount_value:number;target:"subscription"|"implementation";plan_codes:string[];active:boolean;created_at:string};
const planOptions=[{code:"inicial",name:"Start",implementation:true},{code:"profissional",name:"Pro",implementation:true},{code:"imobiliaria",name:"Business",implementation:true},{code:"premium",name:"Prime",implementation:false}];

export default function PlatformCouponManager(){
 const [rows,setRows]=useState<CouponRow[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 const [code,setCode]=useState(""); const [discountType,setDiscountType]=useState<"percent"|"fixed">("percent"); const [value,setValue]=useState("10"); const [target,setTarget]=useState<"subscription"|"implementation">("subscription"); const [plans,setPlans]=useState<string[]>(planOptions.map(p=>p.code));
 const availablePlans=target==="implementation"?planOptions.filter(p=>p.implementation):planOptions;
 const allSelected=availablePlans.length>0&&availablePlans.every(p=>plans.includes(p.code));
 async function load(){if(!supabaseBrowser)return;setLoading(true);const {data,error}=await supabaseBrowser.from("platform_coupons").select("id,code,discount_type,discount_value,target,plan_codes,active,created_at").order("created_at",{ascending:false});setLoading(false);if(error){setMessage(error.message);return}setRows((data||[]) as CouponRow[])}
 useEffect(()=>{void load()},[]);
 const normalizedCode=useMemo(()=>code.trim().toUpperCase().replace(/[^A-Z0-9_-]/g,""),[code]);
 function changeTarget(next:"subscription"|"implementation"){setTarget(next);setPlans(next==="implementation"?planOptions.filter(p=>p.implementation).map(p=>p.code):planOptions.map(p=>p.code))}
 function togglePlan(planCode:string){setPlans(current=>current.includes(planCode)?current.filter(code=>code!==planCode):[...current,planCode])}
 async function submit(event:FormEvent){event.preventDefault();if(!supabaseBrowser||busy)return;const numeric=Number(String(value).replace(",","."));if(!normalizedCode){setMessage("Informe o código do cupom.");return}if(!Number.isFinite(numeric)||numeric<=0){setMessage("Informe um desconto válido.");return}if(discountType==="percent"&&numeric>100){setMessage("O percentual não pode passar de 100%.");return}if(!plans.length){setMessage("Selecione pelo menos um plano.");return}setBusy(true);setMessage("");const {data:user}=await supabaseBrowser.auth.getUser();const result=await supabaseBrowser.from("platform_coupons").insert({code:normalizedCode,discount_type:discountType,discount_value:numeric,target,plan_codes:plans,active:true,created_by:user.user?.id||null});setBusy(false);if(result.error){setMessage(result.error.code==="23505"?"Já existe um cupom com esse código.":result.error.message);return}setCode("");setValue("10");setDiscountType("percent");setTarget("subscription");setPlans(planOptions.map(p=>p.code));setMessage("Cupom criado com sucesso.");await load()}
 async function toggleActive(row:CouponRow){if(!supabaseBrowser)return;await supabaseBrowser.from("platform_coupons").update({active:!row.active}).eq("id",row.id);await load()}
 async function remove(row:CouponRow){if(!supabaseBrowser||!window.confirm(`Excluir o cupom ${row.code}?`))return;const result=await supabaseBrowser.from("platform_coupons").delete().eq("id",row.id);if(result.error){setMessage("Esse cupom já possui vínculo de cobrança e não pode ser excluído. Desative-o.");return}await load()}
 return <section className="couponAdminWrap">
  <style>{`.couponAdminWrap{max-width:1180px;margin:0 auto;padding:30px 20px 60px;color:#15293d}.couponHead{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:22px}.couponHead h1{margin:5px 0 0;font-size:30px}.couponHead p{margin:8px 0 0;color:#66788a}.couponBack{color:#0b2946;font-weight:800;text-decoration:none}.couponGrid{display:grid;grid-template-columns:minmax(300px,430px) 1fr;gap:20px}.couponCard{background:#fff;border:1px solid #dfe6ec;border-radius:18px;padding:22px;box-shadow:0 8px 28px rgba(10,35,58,.06)}.couponCard h2{margin:0 0 18px;font-size:21px}.couponCard label{display:grid;gap:7px;margin:0 0 14px;font-size:12px;font-weight:800;color:#53687a}.couponCard input,.couponCard select{min-height:44px;border:1px solid #cfd9e1;border-radius:10px;padding:9px 11px;font:inherit;background:#fff}.couponPlanChecks{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:7px 0 16px}.couponPlanChecks label{display:flex;align-items:center;gap:8px;margin:0;padding:10px;border:1px solid #e2e8ed;border-radius:10px}.couponPlanChecks label.disabled{opacity:.45;background:#f5f6f7}.couponPlanChecks input{min-height:auto}.couponPrimary{width:100%;min-height:46px;border:0;border-radius:10px;background:#0b2946;color:#fff;font-weight:900;cursor:pointer}.couponList{display:grid;gap:10px}.couponRow{display:grid;grid-template-columns:1.1fr .9fr 1.5fr auto;gap:12px;align-items:center;padding:14px;border:1px solid #e1e7ec;border-radius:12px;background:#f9fbfc}.couponRow strong{display:block}.couponRow small{display:block;color:#718291;margin-top:3px}.couponStatus{display:inline-flex;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:900;background:#eaf6ef;color:#28704a}.couponStatus.off{background:#f1f2f4;color:#6d7780}.couponActions{display:flex;gap:6px}.couponActions button{border:1px solid #ccd7df;background:#fff;border-radius:8px;padding:8px 10px;cursor:pointer;font-weight:800}.couponMsg{margin:12px 0 0;color:#8a6219;font-weight:700;font-size:13px}@media(max-width:850px){.couponGrid{grid-template-columns:1fr}.couponRow{grid-template-columns:1fr}.couponHead{align-items:flex-start;flex-direction:column}.couponActions{justify-content:flex-start}}`}</style>
  <div className="couponHead"><div><span className="eyebrow">PLATAFORMA · CUPONS</span><h1>Cupons de desconto</h1><p>Crie códigos sem exibi-los nas páginas públicas. O desconto só é aplicado quando o cliente informa o código na contratação.</p></div><a className="couponBack" href="../">← Voltar para Plataforma</a></div>
  <div className="couponGrid"><form className="couponCard" onSubmit={submit}><h2>Novo cupom</h2><label>Código<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Ex.: LENOY10" maxLength={32}/></label><label>Tipo de desconto<select value={discountType} onChange={e=>setDiscountType(e.target.value as any)}><option value="percent">Porcentagem (%)</option><option value="fixed">Valor em reais (R$)</option></select></label><label>Valor<input value={value} onChange={e=>setValue(e.target.value)} inputMode="decimal" placeholder={discountType==="percent"?"10":"20,00"}/></label><label>Aplicar em<select value={target} onChange={e=>changeTarget(e.target.value as any)}><option value="subscription">Mensalidade / anuidade</option><option value="implementation">Implantação</option></select></label><div className="couponPlanChecks"><label><input type="checkbox" checked={allSelected} onChange={()=>setPlans(allSelected?[]:availablePlans.map(p=>p.code))}/>Todos</label>{planOptions.map(plan=>{const disabled=target==="implementation"&&!plan.implementation;return <label className={disabled?"disabled":""} key={plan.code}><input type="checkbox" disabled={disabled} checked={plans.includes(plan.code)} onChange={()=>togglePlan(plan.code)}/>{plan.name}{disabled?" · implantação grátis":""}</label>})}</div><button className="couponPrimary" disabled={busy}>{busy?"Salvando...":"Criar cupom"}</button>{message?<p className="couponMsg">{message}</p>:null}</form>
   <div className="couponCard"><h2>Cupons cadastrados</h2>{loading?<p>Carregando...</p>:rows.length===0?<p>Nenhum cupom cadastrado.</p>:<div className="couponList">{rows.map(row=><article className="couponRow" key={row.id}><div><strong>{row.code}</strong><span className={`couponStatus ${row.active?"":"off"}`}>{row.active?"ATIVO":"INATIVO"}</span></div><div><strong>{row.discount_type==="percent"?`${Number(row.discount_value).toLocaleString("pt-BR")}%`:`R$ ${Number(row.discount_value).toLocaleString("pt-BR",{minimumFractionDigits:2})}`}</strong><small>{row.target==="subscription"?"Mensalidade/anuidade":"Implantação"}</small></div><div><strong>{planOptions.filter(p=>row.plan_codes.includes(p.code)).map(p=>p.name).join(", ")}</strong><small>Planos permitidos</small></div><div className="couponActions"><button onClick={()=>void toggleActive(row)}>{row.active?"Desativar":"Ativar"}</button><button onClick={()=>void remove(row)}>Excluir</button></div></article>)}</div>}</div></div>
 </section>
}