const lenoyLogo = "logo-lenoy.svg";

const demoRows = [
  { buyer: "Marina Souza", property: "IM-1042 · Casa com 3 quartos", match: "94%", channel: "WhatsApp", status: "Em revisão" },
  { buyer: "Carlos Mendes", property: "IM-0931 · Apartamento central", match: "89%", channel: "E-mail", status: "Aprovada" },
  { buyer: "Ana Lima", property: "IM-1188 · Sobrado residencial", match: "87%", channel: "WhatsApp", status: "Enviada" },
];

export default function PlatformLanding() {
  return (
    <main className="platformLanding">
      <header className="platformTopbar"><div className="container platformNav"><a className="brand" href="./"><img src={lenoyLogo} alt="LENOY" style={{ width: 112, maxWidth: "28vw", height: "auto", display: "block", borderRadius: 10 }} /></a><nav><a href="#recursos">Recursos</a><a href="#painel-demo">Painel</a><a href="#como-funciona">Como funciona</a><a href="#planos">Planos</a></nav><div className="platformActions"><a className="button secondary" href="login/">Entrar</a><a className="button primary" href="cadastro/">Criar imobiliária</a></div></div></header>

      <section className="container section platformHero"><div><span className="eyebrow">PLATAFORMA SaaS PARA IMOBILIÁRIAS</span><h1>Seu site, seus imóveis, sua equipe. Tudo em um só lugar.</h1><p>Crie a imobiliária, personalize a marca, publique imóveis, organize corretores e leads e use um endereço exclusivo dentro da LENOY ou seu próprio domínio.</p><div className="platformHeroActions"><a className="button primary" href="cadastro/">Começar agora</a><a className="button secondary" href="#painel-demo">Ver painel renovado</a></div><small>Exemplo: suaimobiliaria.imoveis.lenoy.com.br</small></div><div className="platformHeroCard"><span>AMBIENTE DA IMOBILIÁRIA</span><strong>João Imobiliária</strong><div className="platformMiniGrid"><article><small>Imóveis</small><b>42</b></article><article><small>Leads</small><b>18</b></article><article><small>Corretores</small><b>4</b></article><article><small>Oportunidades</small><b>9</b></article></div><div className="platformHeroStatus"><span>IA comercial</span><b>7 oportunidades ativas</b></div></div></section>

      <section className="softSection" id="recursos"><div className="container section"><div className="sectionHeading"><div><span className="eyebrow">RECURSOS</span><h2>Uma plataforma para operar a imobiliária inteira.</h2></div></div><div className="trustGrid"><article><strong>Site exclusivo</strong><p>Marca, cores, contatos e catálogo próprios para cada cliente.</p></article><article><strong>Gestão completa</strong><p>Imóveis, corretores, equipe, leads, visitas, documentos, domínios e histórico em um único painel.</p></article><article><strong>Aplicativo do corretor</strong><p>Cadastro e fotos pelo celular com estrutura de sincronização offline.</p></article><article><strong>IA de oportunidades</strong><p>Identifica imóveis compatíveis com o perfil do comprador e prepara contatos personalizados, respeitando consentimento e regras do plano.</p></article><article><strong>CRM imobiliário</strong><p>Funil, retornos, histórico do cliente, tempo de resposta, visitas e desempenho comercial.</p></article><article><strong>Central de documentos</strong><p>Modelos, versões, anexos privados e checklist documental por imóvel.</p></article></div></div></section>

      <section className="container section" id="painel-demo"><div className="sectionHeading"><div><span className="eyebrow">NOVA VERSÃO VISUAL</span><h2>Painel comercial com leitura rápida do que precisa de atenção.</h2><p className="sectionIntro">Visual demonstrativo com dados fictícios para mostrar a direção atual do produto.</p></div><span className="demoBadge">DEMONSTRAÇÃO</span></div>
      <div className="demoDashboard">
        <div className="demoSidebar"><div><small>IMOBILIÁRIA</small><strong>João Imobiliária</strong></div><a className="active" href="#painel-demo">Visão geral</a><a href="#painel-demo">Imóveis</a><a href="#painel-demo">CRM</a><a href="#painel-demo">Visitas</a><a href="#painel-demo">Oportunidades IA</a><a href="#painel-demo">Documentos</a><a href="#painel-demo">Equipe</a></div>
        <div className="demoContent"><div className="demoTopline"><div><span className="eyebrow">VISÃO COMERCIAL</span><h3>Oportunidades IA</h3><p>Compatibilidade, contato e retorno do comprador em uma única leitura.</p></div><span className="demoLive">● Operação ativa</span></div>
          <div className="demoMetricGrid"><article><small>Contatos no mês</small><strong>38 / 120</strong><span>32% do limite</span></article><article><small>Taxa de resposta</small><strong>47%</strong><span>+8% vs. mês anterior</span></article><article><small>Sinais de interesse</small><strong>11</strong><span>5 pediram detalhes</span></article><article><small>Pedidos de visita</small><strong>4</strong><span>2 para hoje</span></article></div>
          <div className="demoFlow"><article><span>01</span><strong>24</strong><small>Detectadas</small></article><i>→</i><article><span>02</span><strong>9</strong><small>Em revisão</small></article><i>→</i><article><span>03</span><strong>6</strong><small>Aprovadas</small></article><i>→</i><article><span>04</span><strong>15</strong><small>Enviadas</small></article></div>
          <div className="demoTableCard"><div className="demoTableHeader"><div><strong>Compradores com imóvel compatível</strong><span>Filtrar: Todas</span></div></div><div className="demoTable"><div className="demoTableRow demoTableHead"><span>Comprador</span><span>Imóvel</span><span>Match</span><span>Canal</span><span>Situação</span></div>{demoRows.map(row=><div className="demoTableRow" key={row.buyer}><span><b>{row.buyer}</b></span><span>{row.property}</span><span><b>{row.match}</b></span><span>{row.channel}</span><span><em>{row.status}</em></span></div>)}</div></div>
          <div className="demoInsightGrid"><article><span>HORÁRIO SILENCIOSO</span><strong>Livre</strong><small>Envios permitidos neste momento</small></article><article><span>CONSENTIMENTO</span><strong>100%</strong><small>Somente contatos autorizados entram no envio</small></article><article><span>RETORNOS</span><strong>6 novos</strong><small>Incluindo interesse, detalhes e visita</small></article></div>
        </div>
      </div></section>

      <section className="container section" id="como-funciona"><div className="sectionHeading"><div><span className="eyebrow">COMECE EM POUCOS PASSOS</span><h2>Do cadastro ao site da imobiliária.</h2></div></div><div className="steps"><article><span>01</span><h3>Crie a conta</h3><p>Informe os dados da imobiliária e escolha seu endereço na plataforma.</p></article><article><span>02</span><h3>Personalize</h3><p>Cadastre logo, cores, CRECI, WhatsApp e os dados comerciais.</p></article><article><span>03</span><h3>Publique e acompanhe</h3><p>Cadastre imóveis, receba contatos, acompanhe oportunidades e organize o atendimento da equipe.</p></article></div></section>

      <section className="softSection" id="planos"><div className="container section"><div className="sectionHeading"><div><span className="eyebrow">PLANOS</span><h2>Estrutura preparada para crescer com sua imobiliária.</h2><p className="sectionIntro">Preços e limites comerciais serão definidos antes do lançamento.</p></div></div><div className="trustGrid"><article><strong>Essencial</strong><p>Site, subdomínio, imóveis e atendimento.</p></article><article><strong>Profissional</strong><p>Mais usuários, CRM, documentos, relatórios e recursos de IA conforme configuração.</p></article><article><strong>Premium</strong><p>Domínio próprio, maior capacidade e automações comerciais avançadas conforme configuração.</p></article></div></div></section>

      <footer className="container section platformFooter"><div><img src={lenoyLogo} alt="LENOY" style={{ width: 110, height: "auto", display: "block", borderRadius: 10 }} /><p>Plataforma para imobiliárias.</p></div><div><a href="login/">Entrar</a> · <a href="cadastro/">Criar conta</a></div></footer>
    </main>
  );
}
