"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabaseBrowser } from "../lib/supabaseBrowser";

type PlanView = { code:string; name:string; monthly:string; annual:string; implementation:string; implementationFree?:boolean; annualDiscount:number; monthlyValidityDays:number; annualValidityDays:number };
const fallbackPlans: Record<string, PlanView> = {
  inicial:{code:"inicial",name:"Start",monthly:"R$ 39,90/mês",annual:"R$ 359,10/ano",implementation:"R$ 99,00",annualDiscount:25,monthlyValidityDays:30,annualValidityDays:365},
  profissional:{code:"profissional",name:"Pro",monthly:"R$ 59,90/mês",annual:"R$ 539,10/ano",implementation:"R$ 99,00",annualDiscount:25,monthlyValidityDays:30,annualValidityDays:365},
  imobiliaria:{code:"imobiliaria",name:"Business",monthly:"R$ 79,90/mês",annual:"R$ 719,10/ano",implementation:"R$ 100,00",annualDiscount:25,monthlyValidityDays:30,annualValidityDays:365},
  premium:{code:"premium",name:"Prime",monthly:"R$ 110,00/mês",annual:"R$ 990,00/ano",implementation:"Grátis",implementationFree:true,annualDiscount:25,monthlyValidityDays:30,annualValidityDays:365},
};
function brl(value:unknown){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value||0));}
function queryValue(name:string){ if(typeof window==="undefined")return ""; return new URLSearchParams(window.location.search).get(name)||""; }
function slugify(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").replace(/-+/g,"-").slice(0,48)}
function Header(){return <header className="prepaidTopbar"><a href="/"><img src="/lenoy-imobiliarias-logo-20260826.png" alt="LENOY IMOBILIÁRIAS"/></a><nav><a href="/demonstracao/">Demonstração</a><a href="/planos/">Planos</a><a href="/login/">Entrar</a></nav></header>}
function billingError(value:unknown){const code=String(value||"");if(code.includes("billing_blocked_by_release_control"))return "Os pagamentos reais ainda estão temporariamente bloqueados pela administração da plataforma.";if(code.includes("valid_email_required"))return "Informe um e-mail válido.";if(code.includes("infinitepay_not_configured"))return "O pagamento ainda não está disponível.";if(code.includes("coupon_invalid"))return "Cupom inválido ou inativo.";if(code.includes("coupon_not_for_plan"))return "Este cupom não se aplica ao plano escolhido.";if(code.includes("coupon_not_for_charge"))return "Este cupom é destinado à implantação e não se aplica a esta cobrança.";if(code.includes("coupon_zeros_charge"))return "O desconto deste cupom é maior ou igual ao valor da cobrança.";return code||"Não foi possível abrir o pagamento agora."}

export function PrepaidCheckout(){
  const [ready,setReady]=useState(false); const [email,setEmail]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const [planCode,setPlanCode]=useState(""); const [plan,setPlan]=useState<PlanView|null>(null); const [cycle,setCycle]=useState<"monthly"|"annual">("monthly");
  const [coupon,setCoupon]=useState(""); const [couponBusy,setCouponBusy]=useState(false); const [couponMessage,setCouponMessage]=useState(""); const [couponPreview,setCouponPreview]=useState<any>(null);
  useEffect(()=>{const code=queryValue("plano").toLowerCase();const fallback=fallbackPlans[code]||null;setPlanCode(code);setPlan(fallback);setCycle(queryValue("ciclo")==="annual"?"annual":"monthly");setReady(true);if(!supabaseBrowser||!code)return;let active=true;void supabaseBrowser.from("subscription_plans").select("code,name,monthly_price,annual_price,implementation_fee,annual_discount_percent,monthly_validity_days,annual_validity_days,features,active").eq("code",code).eq("active",true).maybeSingle().then(({data,error})=>{if(!active||error||!data)return;const fee=Number(data.implementation_fee||0);setPlan({code:String(data.code),name:String(data.name),monthly:`${brl(data.monthly_price)}/mês`,annual:`${brl(data.annual_price)}/ano`,implementation:fee>0?brl(fee):"Grátis",implementationFree:fee<=0,annualDiscount:Number(data.annual_discount_percent??25),monthlyValidityDays:Number(data.monthly_validity_days||30),annualValidityDays:Number(data.annual_validity_days||365)});});return()=>{active=false};},[]);
  async function applyCoupon(){if(!supabaseBrowser||!plan||!coupon.trim())return;setCouponBusy(true);setCouponMessage("");setCouponPreview(null);const result=await supabaseBrowser.functions.invoke("create-prepaid-infinitepay-checkout",{body:{plan_code:plan.code,billing_cycle:cycle,coupon_code:coupon.trim().toUpperCase(),preview_only:true}});setCouponBusy(false);if(result.error||result.data?.error){setCouponMessage(billingError(result.data?.error||result.error?.message));return}setCouponPreview(result.data);setCouponMessage(result.data?.deferred?`Cupom aplicado. O desconto será usado na primeira ${cycle==="annual"?"anuidade":"mensalidade"} após a implantação.`:`Cupom aplicado: economia de ${brl(result.data?.savings)}. Valor com desconto: ${brl(result.data?.final_amount)}.`)}
  async function submit(event:FormEvent){event.preventDefault();if(!supabaseBrowser||!plan)return;setBusy(true);setMessage("");const result=await supabaseBrowser.functions.invoke("create-prepaid-infinitepay-checkout",{body:{email,plan_code:plan.code,billing_cycle:cycle,coupon_code:couponPreview?coupon.trim().toUpperCase():""}});setBusy(false);if(result.error||result.data?.error){setMessage(billingError(result.data?.error||result.error?.message));return}const url=String(result.data?.checkout_url||"");if(!url){setMessage("O pagamento não retornou um endereço válido.");return}window.location.assign(url)}
  if(!ready)return <main className="prepaidPage"><Header/><section className="prepaidCard"><h1>Preparando pagamento...</h1></section></main>;
  if(!plan||!planCode)return <main className="prepaidPage"><Header/><section className="prepaidCard"><span className="eyebrow">CONTRATAÇÃO</span><h1>Escolha um plano primeiro.</h1><p>Volte aos planos e escolha a opção mensal ou anual.</p><a className="button primary full" href="/planos/">Ver planos</a></section></main>;
  return <main className="prepaidPage"><Header/><section className="prepaidCheckoutShell"><div className="prepaidIntro"><span className="eyebrow">PAGAMENTO PRIMEIRO</span><h1>Contrate agora. Configure sua imobiliária depois.</h1><p>Informe somente o e-mail que receberá a confirmação e o link de configuração. Nome, imobiliária, endereço do site e senha serão solicitados somente depois que o pagamento for confirmado.</p></div><form className="prepaidCard" onSubmit={submit}><div className="prepaidSelectedPlan"><small>PLANO ESCOLHIDO</small><strong>{plan.name}</strong><span>{cycle==="annual"?`Anual · ${plan.annualDiscount.toLocaleString("pt-BR")}% OFF`:"Mensal"}</span></div>{cycle==="monthly"?<div className="prepaidPrice"><b>{plan.implementationFree?plan.monthly:plan.implementation}</b><span>{plan.implementationFree?`Implantação grátis. Primeira cobrança: ${plan.monthly}. Validade: ${plan.monthlyValidityDays} dias.`:`Primeiro pagamento: implantação. A mensalidade de ${plan.monthly} vence após ${plan.monthlyValidityDays} dias.`}</span></div>:<div className="prepaidPrice annual"><b>{plan.annual}</b><span>{plan.annualValidityDays} dias de validade com {plan.annualDiscount.toLocaleString("pt-BR")}% de desconto e implantação grátis.</span></div>}<label>E-mail para receber a ativação<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="seuemail@exemplo.com" required autoComplete="email"/></label><label>Cupom de desconto<div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8}}><input value={coupon} onChange={e=>{setCoupon(e.target.value.toUpperCase());setCouponPreview(null);setCouponMessage("")}} placeholder="Digite seu cupom"/><button type="button" className="button secondary" onClick={()=>void applyCoupon()} disabled={couponBusy||!coupon.trim()}>{couponBusy?"Validando...":"Aplicar"}</button></div></label>{couponMessage?<p className="formMessage" style={{marginTop:-4}}>{couponMessage}</p>:null}<button className="button primary full prepaidPayButton" disabled={busy}>{busy?"Abrindo pagamento...":"Ir para pagamento seguro"}</button><small className="prepaidNote">Nenhuma imobiliária é criada antes do pagamento. Após a confirmação da InfinitePay, enviaremos o link para configurar seu acesso.</small>{message?<p className="formMessage">{message}</p>:null}<a className="backLink" href="/planos/">← Trocar plano</a></form></section></main>
}

export function PaymentReturn(){
  const [status,setStatus]=useState<any>(null); const [message,setMessage]=useState("Aguardando a confirmação segura do pagamento...");
  const purchaseId=typeof window!=="undefined"?queryValue("pedido"):""; const token=typeof window!=="undefined"?queryValue("token"):"";
  useEffect(()=>{if(!supabaseBrowser||!purchaseId||!token)return;let active=true;let timer:number|undefined;const check=async()=>{const result=await supabaseBrowser!.functions.invoke("prepaid-purchase-status",{body:{purchase_id:purchaseId,status_token:token}});if(!active)return;if(result.error||result.data?.error){setMessage("Não foi possível consultar este pagamento agora.");return}setStatus(result.data);if(result.data?.completed){setMessage("Configuração concluída. Sua imobiliária já foi criada.");return}if(result.data?.paid&&result.data?.invite_sent){setMessage(`Pagamento confirmado. Enviamos para ${result.data.email} o link seguro para criar sua imobiliária.`);return}if(result.data?.paid){setMessage("Pagamento confirmado. Estamos preparando o e-mail com o link de configuração.");timer=window.setTimeout(check,3500);return}setMessage("Pagamento retornou. Aguardando a confirmação da InfinitePay no servidor...");timer=window.setTimeout(check,3500)};void check();return()=>{active=false;if(timer)window.clearTimeout(timer)}},[purchaseId,token]);
  return <main className="prepaidPage"><Header/><section className="prepaidCard paymentReturnCard"><span className="eyebrow">PÓS-PAGAMENTO</span><h1>{status?.paid?"Pagamento confirmado.":"Estamos confirmando seu pagamento."}</h1><p>{message}</p>{status?.paid?<div className="returnSteps"><span>1. Pagamento confirmado</span><span>2. E-mail de ativação</span><span>3. Crie nome, site e senha</span><span>4. Acesse painel, site e aplicativo</span></div>:null}<p className="prepaidHelp">Não feche o e-mail de ativação: o link é pessoal e libera somente a contratação que foi paga.</p><a className="button secondary full" href="/demonstracao/">Ver demonstração novamente</a></section></main>
}

export function PrepaidOnboarding(){
  const [sessionReady,setSessionReady]=useState(false); const [email,setEmail]=useState(""); const [fullName,setFullName]=useState(""); const [agencyName,setAgencyName]=useState(""); const [agencySlug,setAgencySlug]=useState(""); const [slugTouched,setSlugTouched]=useState(false); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const purchaseId=typeof window!=="undefined"?queryValue("pedido"):""; const token=typeof window!=="undefined"?queryValue("token"):"";
  useEffect(()=>{if(!supabaseBrowser){setSessionReady(true);return}let active=true;void supabaseBrowser.auth.getSession().then(({data})=>{if(!active)return;setEmail(data.session?.user.email||"");setFullName(String(data.session?.user.user_metadata?.full_name||""));setSessionReady(true)});const {data:listener}=supabaseBrowser.auth.onAuthStateChange((_event,session)=>{if(!active)return;setEmail(session?.user.email||"");setFullName(String(session?.user.user_metadata?.full_name||""));setSessionReady(true)});return()=>{active=false;listener.subscription.unsubscribe()}},[]);
  useEffect(()=>{if(!slugTouched)setAgencySlug(slugify(agencyName))},[agencyName,slugTouched]);
  const address=useMemo(()=>`${agencySlug||"sua-imobiliaria"}.imoveis.lenoy.com.br`,[agencySlug]);
  async function submit(event:FormEvent){event.preventDefault();if(!supabaseBrowser)return;if(password.length<8){setMessage("Use uma senha com pelo menos 8 caracteres.");return}if(password!==confirm){setMessage("As senhas não conferem.");return}setBusy(true);setMessage("");const result=await supabaseBrowser.functions.invoke("complete-prepaid-onboarding",{body:{purchase_id:purchaseId,onboarding_token:token,full_name:fullName,agency_name:agencyName,agency_slug:agencySlug,password}});setBusy(false);if(result.error||result.data?.error){const code=String(result.data?.error||result.error?.message||"");setMessage(code.includes("slug_unavailable")?"Esse endereço já está em uso. Escolha outro.":code.includes("expired")?"Este link de configuração expirou.":code||"Não foi possível concluir a configuração.");return}window.location.assign(String(result.data?.redirect||"/admin/"))}
  if(!sessionReady)return <main className="prepaidPage"><Header/><section className="prepaidCard"><h1>Validando seu link...</h1></section></main>;
  if(!email)return <main className="prepaidPage"><Header/><section className="prepaidCard"><span className="eyebrow">LINK DE ATIVAÇÃO</span><h1>Abra esta página pelo e-mail recebido.</h1><p>O link do e-mail confirma sua identidade e a contratação paga antes de liberar a criação da imobiliária.</p><a className="button secondary full" href="/login/">Já tenho acesso</a></section></main>;
  return <main className="prepaidPage"><Header/><section className="prepaidCheckoutShell onboardingShell"><div className="prepaidIntro"><span className="eyebrow">PAGAMENTO CONFIRMADO</span><h1>Agora crie sua imobiliária.</h1><p>O pagamento já foi confirmado. Falta somente configurar os dados que aparecerão no seu ambiente.</p></div><form className="prepaidCard" onSubmit={submit}><label>Seu nome completo<input value={fullName} onChange={e=>setFullName(e.target.value)} required/></label><label>Nome da imobiliária<input value={agencyName} onChange={e=>setAgencyName(e.target.value)} placeholder="Ex.: Alameda Imóveis" required/></label><label>Endereço do site<div className="prepaidSlug"><input value={agencySlug} onChange={e=>{setSlugTouched(true);setAgencySlug(slugify(e.target.value))}} required/><span>.imoveis.lenoy.com.br</span></div></label><small className="prepaidAddress">Seu site: {address}</small><label>E-mail confirmado<input value={email} readOnly disabled/></label><label>Crie sua senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></label><label>Confirme a senha<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={8} required/></label><button className="button primary full" disabled={busy}>{busy?"Criando sua imobiliária...":"Criar imobiliária e acessar"}</button>{message?<p className="formMessage">{message}</p>:null}</form></section></main>
}
