"use client";

import { useEffect, useMemo, useState } from "react";
import { supabaseBrowser } from "../lib/supabaseBrowser";

type PlanRow={id?:string;code:string;name:string;description:string|null;monthly_price:number|null;annual_price:number|null;implementation_fee:number|null;annual_discount_percent:number|null;monthly_validity_days:number;annual_validity_days:number;max_properties:number|null;max_users:number|null;max_ai_descriptions:number|null;features:Record<string,unknown>|null;active?:boolean;display_order:number};
type CardRow={id:string;label:string;included:boolean};

const fallbackPlans:PlanRow[]=[
 {code:"inicial",name:"Start",description:"Para começar com a estrutura essencial da imobiliária.",monthly_price:39.90,annual_price:359.10,implementation_fee:99,annual_discount_percent:25,monthly_validity_days:30,annual_validity_days:365,max_properties:30,max_users:1,max_ai_descriptions:5,display_order:10,features:{max_concurrent_accesses:2,max_professional_emails:1,max_photos_per_property:5,property_catalog:true,property_portals:true,whatsapp_site:true,seo_site:true,exclusive_site:true,crm_real_estate:true,customer_management:true,email_leads:true,push_notifications:true,ai_descriptions:true}},
 {code:"profissional",name:"Pro",description:"Para quem precisa de gestão completa e mais capacidade.",monthly_price:59.90,annual_price:539.10,implementation_fee:99,annual_discount_percent:25,monthly_validity_days:30,annual_validity_days:365,max_properties:400,max_users:3,max_ai_descriptions:15,display_order:20,features:{featured:true,max_concurrent_accesses:6,max_professional_emails:3,max_photos_per_property:50,property_catalog:true,property_portals:true,facebook_lead_ads:true,whatsapp_site:true,seo_site:true,exclusive_site:true,full_management:true,broker_app:true,crm_real_estate:true,customer_management:true,sales_management:true,key_control:true,proposal_control:true,visit_agenda:true,inspections:true,email_leads:true,push_notifications:true,ai_descriptions:true}},
 {code:"imobiliaria",name:"Business",description:"Para equipes com operação comercial, documentos e inteligência artificial.",monthly_price:79.90,annual_price:719.10,implementation_fee:100,annual_discount_percent:25,monthly_validity_days:30,annual_validity_days:365,max_properties:1000,max_users:5,max_ai_descriptions:30,display_order:30,features:{max_concurrent_accesses:10,max_professional_emails:5,max_photos_per_property:50,property_catalog:true,property_portals:true,facebook_lead_ads:true,whatsapp_site:true,seo_site:true,exclusive_site:true,full_management:true,broker_app:true,crm_real_estate:true,customer_management:true,sales_management:true,key_control:true,proposal_control:true,visit_agenda:true,inspections:true,documents:true,advanced_lead_reservation:true,user_permissions:true,strategic_reports:true,email_leads:true,push_notifications:true,ai_descriptions:true,ai_buyer_outreach:true,buyer_property_matching:true,consented_auto_outreach:true}},
 {code:"premium",name:"Prime",description:"Para operações maiores com domínio próprio, equipes e automações avançadas.",monthly_price:110,annual_price:990,implementation_fee:0,annual_discount_percent:25,monthly_validity_days:30,annual_validity_days:365,max_properties:3000,max_users:10,max_ai_descriptions:50,display_order:40,features:{max_concurrent_accesses:20,max_professional_emails:10,max_photos_per_property:50,property_catalog:true,property_portals:true,facebook_lead_ads:true,whatsapp_site:true,seo_site:true,exclusive_site:true,full_management:true,broker_app:true,crm_real_estate:true,customer_management:true,sales_management:true,key_control:true,proposal_control:true,visit_agenda:true,inspections:true,documents:true,advanced_lead_reservation:true,user_permissions:true,strategic_reports:true,multi_team:true,custom_domain:true,email_leads:true,push_notifications:true,ai_descriptions:true,ai_buyer_outreach:true,buyer_property_matching:true,consented_auto_outreach:true,priority_operations:true,advanced_automation:true}},
];

const featureLabels:[string,string][]=[
 ["property_catalog","Catálogo de imóveis"],["exclusive_site","Site exclusivo"],["property_portals","Portais imobiliários"],["facebook_lead_ads","Facebook Lead Ads"],["whatsapp_site","WhatsApp flutuante no site"],["seo_site","Site otimizado para SEO"],["full_management","Gestão completa"],["broker_app","Aplicativo do corretor"],["crm_real_estate","CRM imobiliário"],["customer_management","Gestão de clientes"],["sales_management","Gestão de vendas"],["key_control","Controle de chaves"],["proposal_control","Controle de propostas"],["visit_agenda","Agenda e visitas"],["inspections","Vistorias"],["advanced_lead_reservation","Reserva avançada de leads"],["user_permissions","Permissões por usuário"],["strategic_reports","Relatórios estratégicos"],["documents","Central de documentos"],["multi_team","Gestão multi-equipe"],["custom_domain","Domínio próprio"],["ai_buyer_outreach","IA de oportunidades"],["buyer_property_matching","Matching comprador × imóvel"],["consented_auto_outreach","Contato automático com consentimento"],["priority_operations","Prioridade operacional"],["advanced_automation","Recursos avançados de automação"],["push_notifications","Notificações push"],["email_leads","Contatos por e-mail"],
];

function features(plan:PlanRow){return plan.features||{};}
function enabled(plan:PlanRow,key:string){return Boolean(features(plan)[key]);}
function featureNumber(plan:PlanRow,key:string){const value=Number(features(plan)[key]);return Number.isFinite(value)&&value>=0?value:null;}
function money(value:number|null){return new Intl.NumberFormat("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value||0));}
function number(value:number|null){return value==null?"—":Number(value).toLocaleString("pt-BR");}
function yes(value:boolean){return value?"✓":"—";}
function extras(plan:PlanRow){const value=features(plan).public_benefits;return Array.isArray(value)?value.map(String).map(item=>item.trim()).filter(Boolean):[];}
function normalized(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLocaleLowerCase("pt-BR");}

function cardRows(plan:PlanRow,extraLabels:string[]):CardRow[]{
 const access=featureNumber(plan,"max_concurrent_accesses"),emails=featureNumber(plan,"max_professional_emails"),photos=featureNumber(plan,"max_photos_per_property");
 const rows:CardRow[]=[
  {id:"max_properties",included:plan.max_properties!=null,label:plan.max_properties!=null?`Até ${number(plan.max_properties)} imóveis`:"Limite de imóveis"},
  {id:"max_users",included:plan.max_users!=null,label:plan.max_users!=null?(plan.max_users===1?"1 usuário":`Até ${number(plan.max_users)} usuários`):"Usuários"},
  {id:"max_concurrent_accesses",included:access!=null,label:access!=null?`${access} acessos simultâneos`:"Acessos simultâneos"},
  {id:"max_professional_emails",included:emails!=null,label:emails!=null?`${emails} ${emails===1?"e-mail profissional":"e-mails profissionais"}`:"E-mails profissionais"},
  {id:"max_photos_per_property",included:photos!=null,label:photos!=null?`${photos} fotos por imóvel`:"Fotos por imóvel"},
  ...featureLabels.map(([key,label])=>({id:key,label,included:enabled(plan,key)})),
  {id:"ai_descriptions",included:enabled(plan,"ai_descriptions"),label:enabled(plan,"ai_descriptions")?`${number(plan.max_ai_descriptions)} descrições com IA/mês`:"Descrições com IA/mês"},
 ];
 const ownExtras=new Set(extras(plan).map(normalized));
 extraLabels.forEach((label,index)=>rows.push({id:`extra-${index}-${normalized(label)}`,label,included:ownExtras.has(normalized(label))}));
 return rows;
}

export default function PublicPlansCatalog(){
 const [plans,setPlans]=useState<PlanRow[]>(fallbackPlans);
 useEffect(()=>{if(!supabaseBrowser)return;let active=true;void supabaseBrowser.from("subscription_plans").select("id,code,name,description,monthly_price,annual_price,implementation_fee,annual_discount_percent,monthly_validity_days,annual_validity_days,max_properties,max_users,max_ai_descriptions,features,active,display_order").eq("active",true).order("display_order").then(({data,error})=>{if(!active||error||!data?.length)return;const publicRows=(data as PlanRow[]).filter(plan=>String(plan.features?.internal_only||"false").toLowerCase()!=="true");if(publicRows.length)setPlans(publicRows);});return()=>{active=false};},[]);
 const extraLabels=useMemo(()=>{const standard=new Set(featureLabels.map(([,label])=>normalized(label)));const found=new Map<string,string>();plans.forEach(plan=>extras(plan).forEach(label=>{const key=normalized(label);if(key&&!standard.has(key)&&!found.has(key))found.set(key,label);}));return Array.from(found.values());},[plans]);
 const compareRows=useMemo(()=>[
  ["Imóveis",...plans.map(p=>number(p.max_properties))],["Usuários",...plans.map(p=>number(p.max_users))],["Acessos simultâneos",...plans.map(p=>number(featureNumber(p,"max_concurrent_accesses")))],["E-mails profissionais",...plans.map(p=>number(featureNumber(p,"max_professional_emails")))],["Fotos por imóvel",...plans.map(p=>number(featureNumber(p,"max_photos_per_property")))],
  ["Portais imobiliários",...plans.map(p=>yes(enabled(p,"property_portals")))],["Facebook Lead Ads",...plans.map(p=>yes(enabled(p,"facebook_lead_ads")))],["WhatsApp no site",...plans.map(p=>yes(enabled(p,"whatsapp_site")))],["Domínio próprio",...plans.map(p=>yes(enabled(p,"custom_domain")))],["Site exclusivo",...plans.map(p=>yes(enabled(p,"exclusive_site")))],["Gestão completa",...plans.map(p=>yes(enabled(p,"full_management")))],["Aplicativo do corretor",...plans.map(p=>yes(enabled(p,"broker_app")))],["CRM imobiliário",...plans.map(p=>enabled(p,"crm_real_estate")?(enabled(p,"full_management")?"Completo":"Básico"):"—")],["Gestão de clientes",...plans.map(p=>yes(enabled(p,"customer_management")))],["Gestão de vendas",...plans.map(p=>yes(enabled(p,"sales_management")))],["Controle de chaves",...plans.map(p=>yes(enabled(p,"key_control")))],["Controle de propostas",...plans.map(p=>yes(enabled(p,"proposal_control")))],["Agenda e visitas",...plans.map(p=>yes(enabled(p,"visit_agenda")))],["Vistorias",...plans.map(p=>yes(enabled(p,"inspections")))],["Reserva avançada de leads",...plans.map(p=>yes(enabled(p,"advanced_lead_reservation")))],["Permissões por usuário",...plans.map(p=>yes(enabled(p,"user_permissions")))],["Relatórios estratégicos",...plans.map(p=>yes(enabled(p,"strategic_reports")))],["Central de documentos",...plans.map(p=>yes(enabled(p,"documents")))],["Gestão multi-equipe",...plans.map(p=>yes(enabled(p,"multi_team")))],["Descrições com IA",...plans.map(p=>enabled(p,"ai_descriptions")?`${number(p.max_ai_descriptions)}/mês`:"—")],["IA de oportunidades",...plans.map(p=>yes(enabled(p,"ai_buyer_outreach")))],["Matching comprador × imóvel",...plans.map(p=>yes(enabled(p,"buyer_property_matching")))],["Contato automático com consentimento",...plans.map(p=>yes(enabled(p,"consented_auto_outreach")))],["Validade mensal",...plans.map(p=>`${p.monthly_validity_days||30} dias`)],["Validade anual",...plans.map(p=>`${p.annual_validity_days||365} dias`)],["Implantação no mensal",...plans.map(p=>Number(p.implementation_fee||0)>0?`R$ ${money(p.implementation_fee)}`:"Grátis")],["Implantação no anual",...plans.map(()=>"Grátis")],["Desconto no anual",...plans.map(p=>`${Number(p.annual_discount_percent??25).toLocaleString("pt-BR")}%`)],
 ],[plans]);
 return <>
  <section className="standalonePlansGrid" aria-label="Planos disponíveis">{plans.map(plan=>{const free=Number(plan.implementation_fee||0)<=0,discount=Number(plan.annual_discount_percent??25);return <article key={plan.code} className={`standalonePlanCard ${enabled(plan,"featured")?"featured":""}`}>{enabled(plan,"featured")?<span className="standalonePlanBadge">MAIS ESCOLHIDO</span>:<span className="standalonePlanTag">PLANO</span>}<h2>{plan.name}</h2><p className="standalonePlanSummary">{plan.description||"Plano LENOY IMOBILIÁRIAS."}</p><div className="standalonePriceMain"><strong>R$ {money(plan.monthly_price)}</strong><span>/mês</span></div><div className="standaloneCycleBox"><div><small>MENSAL</small><b>R$ {money(plan.monthly_price)}/mês</b>{free?<span>Implantação grátis</span>:<span>Primeiro pagamento: implantação de R$ {money(plan.implementation_fee)}</span>}</div><a href={`/contratar/?plano=${encodeURIComponent(plan.code)}&ciclo=monthly`}>Contratar mensal</a></div><div className="standaloneCycleBox annual"><div><small>ANUAL · {discount.toLocaleString("pt-BR")}% OFF</small><b>R$ {money(plan.annual_price)}/ano</b><span>Implantação grátis</span></div><a href={`/contratar/?plano=${encodeURIComponent(plan.code)}&ciclo=annual`}>Contratar anual</a></div><div className="standalonePlanFeatures">{cardRows(plan,extraLabels).map(row=><span key={row.id} className={row.included?"included":"excluded"}><b aria-label={row.included?"Incluído":"Não incluído"}>{row.included?"✓":"—"}</b><em>{row.label}</em></span>)}</div></article>})}</section>
  <div className="standaloneCompareJump"><a href="#comparativo">Comparar todos os planos</a></div>
  <section id="comparativo" className="standaloneCompareSection"><div className="standaloneCompareHeading"><span>COMPARATIVO</span><h2>Compare recurso por recurso.</h2><p>Escolha a coluna do plano que atende melhor sua operação e siga para o pagamento.</p></div><div className="standaloneCompareScroller"><table className="standaloneCompareTable"><thead><tr><th>Recurso</th>{plans.map(plan=><th key={plan.code}>{plan.name}</th>)}</tr></thead><tbody>{compareRows.map(row=><tr key={String(row[0])}><td>{row[0]}</td>{row.slice(1).map((value,index)=><td key={`${row[0]}-${index}`}>{value}</td>)}</tr>)}</tbody><tfoot><tr><td>Contratar</td>{plans.map(plan=><td key={plan.code}><a href={`/contratar/?plano=${encodeURIComponent(plan.code)}&ciclo=monthly`}>Escolher {plan.name}</a></td>)}</tr></tfoot></table></div></section>
 </>;
}
